// Generated by: setup
// TypeWriter: List
// Directive: +test on Num

package main

import (
	"bytes"
	"fmt"
	"math/rand"
	"sort"
)

//-------------------------------------------------------------------------------------------------

// NumCollection is an interface for collections of type Num, including sets, lists and options (where present).
type NumCollection interface {
	// Size gets the size/length of the collection.
	Size() int

	// IsEmpty returns true if the collection is empty.
	IsEmpty() bool

	// NonEmpty returns true if the collection is non-empty.
	NonEmpty() bool

	// IsSequence returns true for lists, but false otherwise.
	IsSequence() bool

	// IsSet returns true for sets, but false otherwise.
	IsSet() bool

	// Head returns the first element of a list or an arbitrary element of a set or the contents of an option.
	// Panics if the collection is empty.
	Head() Num

	// ToSlice returns a plain slice containing all the elements in the collection. This is useful for bespoke iteration etc.
	// For sequences, the order of the elements is simple and well defined.
	// For non-sequences (i.e. sets) the order of the elements is stable but not well defined. This means it will give
	// the same order each subsequent time it is used as it did the first time.
	ToSlice() []Num

	// ToInts gets all the elements in a slice of the underlying type, []int.
	ToInts() []int

	// ToList gets all the elements in a List.
	ToList() NumList

	// ToSet gets all the elements in a Set.
	ToSet() NumSet

	// Send sends all elements along a channel of type Num.
	// For sequences, the order of the elements is simple and well defined.
	// For non-sequences (i.e. sets) the order of the elements is stable but not well defined. This means it will give
	// the same order each subsequent time it is used as it did the first time.
	Send() <-chan Num

	// Exists returns true if there exists at least one element in the collection that matches
	// the predicate supplied.
	Exists(predicate func(Num) bool) bool

	// Forall returns true if every element in the collection matches the predicate supplied.
	Forall(predicate func(Num) bool) bool

	// Foreach iterates over every element, executing a supplied function against each.
	Foreach(fn func(Num))

	// Filter returns a new NumCollection whose elements return true for a predicate function.
	// The relative order of the elements in the result is the same as in the
	// original collection.
	Filter(predicate func(Num) bool) (result NumCollection)

	// Partition returns two new NumCollections whose elements return true or false for the predicate, p.
	// The first consists of all elements that satisfy the predicate and the second consists of
	// all elements that don't. The relative order of the elements in the results is the same as in the
	// original collection.
	Partition(p func(Num) bool) (matching NumCollection, others NumCollection)

	// Equals verifies that another NumCollection has the same size and elements as this one. Also,
	// if the collection is a sequence, the order must be the same.
	// Omitted if Num is not comparable.
	Equals(other NumCollection) bool

	// Contains tests whether a given value is present in the collection.
	// Omitted if Num is not comparable.
	Contains(value Num) bool

	// Sum sums Num elements.
	// Omitted if Num is not numeric.
	Sum() Num

	// Mean computes the arithmetic mean of all elements. Panics if the collection is empty.
	// Omitted if Num is not numeric.
	Mean() float64

	// Min returns the minimum value of NumList. In the case of multiple items being equally minimal,
	// the first such element is returned. Panics if the collection is empty.
	Min() Num

	// Max returns the maximum value of NumList. In the case of multiple items being equally maximal,
	// the first such element is returned. Panics if the collection is empty.
	Max() Num

	// String gets a string representation of the collection. "[" and "]" surround
	// a comma-separated list of the elements.
	String() string

	// MkString gets a string representation of the collection. "[" and "]" surround a list
	// of the elements joined by the separator you provide.
	MkString(sep string) string

	// MkString3 gets a string representation of the collection. 'pfx' and 'sfx' surround a list
	// of the elements joined by the 'mid' separator you provide.
	MkString3(pfx, mid, sfx string) string
}

//-------------------------------------------------------------------------------------------------

// NumList is a slice of type Num. Use it where you would use []Num.
// List values follow a similar pattern to Scala Lists and LinearSeqs in particular.
// Importantly, *none of its methods ever mutate a list*; they merely return new lists where required.
// When a list needs mutating, use normal Go slice operations, e.g. *append()*.
// For comparison with Scala, see e.g. http://www.scala-lang.org/api/2.11.7/#scala.collection.LinearSeq
type NumList []Num

//-------------------------------------------------------------------------------------------------

// NewNumList constructs a new list containing the supplied values, if any.
func NewNumList(values ...Num) NumList {
	list := make(NumList, len(values))
	for i, v := range values {
		list[i] = v
	}
	return list
}

// NewNumListFromInts constructs a new NumList from a []int.
func NewNumListFromInts(values []int) NumList {
	list := make(NumList, len(values))
	for i, v := range values {
		list[i] = Num(v)
	}
	return list
}

// BuildNumListFromChan constructs a new NumList from a channel that supplies a sequence
// of values until it is closed. The function doesn't return until then.
func BuildNumListFromChan(source <-chan Num) NumList {
	result := make(NumList, 0)
	for v := range source {
		result = append(result, v)
	}
	return result
}

//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------

// Head gets the first element in the list. Head plus Tail include the whole list. Head is the opposite of Last.
// Panics if list is empty
func (list NumList) Head() Num {
	return list[0]
}

// Last gets the last element in the list. Init plus Last include the whole list. Last is the opposite of Head.
// Panics if list is empty
func (list NumList) Last() Num {
	return list[len(list)-1]
}

// Tail gets everything except the head. Head plus Tail include the whole list. Tail is the opposite of Init.
// Panics if list is empty
func (list NumList) Tail() NumCollection {
	return NumList(list[1:])
}

// Init gets everything except the last. Init plus Last include the whole list. Init is the opposite of Tail.
// Panics if list is empty
func (list NumList) Init() NumCollection {
	return NumList(list[:len(list)-1])
}

// IsEmpty tests whether NumList is empty.
func (list NumList) IsEmpty() bool {
	return len(list) == 0
}

// NonEmpty tests whether NumList is empty.
func (list NumList) NonEmpty() bool {
	return len(list) > 0
}

// IsSequence returns true for lists.
func (list NumList) IsSequence() bool {
	return true
}

// IsSet returns false for lists.
func (list NumList) IsSet() bool {
	return false
}

//-------------------------------------------------------------------------------------------------

// ToSlice gets all the list's elements in a plain slice. This is simply a type conversion and is hardly needed
// for lists, because the underlying type can be used directly also.
// It is part of the NumCollection interface.
func (list NumList) ToSlice() []Num {
	return []Num(list)
}

// ToInts gets all the elements in a []int.
func (list NumList) ToInts() []int {
	slice := make([]int, len(list))
	for i, v := range list {
		slice[i] = int(v)
	}
	return slice
}

// ToList simply returns the list in this case, but is part of the Collection interface.
func (list NumList) ToList() NumList {
	return list
}

// ToSet gets all the list's elements in a NumSet.
func (list NumList) ToSet() NumSet {
	set := make(map[Num]struct{})
	for _, v := range list {
		set[v] = struct{}{}
	}
	return NumSet(set)
}

//-------------------------------------------------------------------------------------------------

// Size returns the number of items in the list - an alias of Len().
func (list NumList) Size() int {
	return len(list)
}

// Len returns the number of items in the list - an alias of Size().
// This is one of the three methods in the standard sort.Interface.
func (list NumList) Len() int {
	return len(list)
}

// Swap exchanges two elements, which is neceessary during sorting etc.
// This is one of the three methods in the standard sort.Interface.
func (list NumList) Swap(i, j int) {
	list[i], list[j] = list[j], list[i]
}

// These methods require that Num be ordered.

// Less determines whether one specified element is less than another specified element.
// This is one of the three methods in the standard sort.Interface.
func (list NumList) Less(i, j int) bool {
	return list[i] < list[j]
}

// Sort returns a new ordered NumList.
func (list NumList) Sort() NumList {
	result := make(NumList, len(list))
	copy(result, list)
	sort.Sort(result)
	return result
}

// IsSorted reports whether NumList is sorted.
func (list NumList) IsSorted() bool {
	return sort.IsSorted(list)
}

// SortDesc returns a new reverse-ordered NumList.
func (list NumList) SortDesc() NumList {
	result := make(NumList, len(list))
	copy(result, list)
	sort.Sort(sort.Reverse(result))
	return result
}

// IsSortedDesc reports whether NumList is reverse-sorted.
func (list NumList) IsSortedDesc() bool {
	return sort.IsSorted(sort.Reverse(list))
}

//-------------------------------------------------------------------------------------------------

// Exists verifies that one or more elements of NumList return true for the passed func.
func (list NumList) Exists(fn func(Num) bool) bool {
	for _, v := range list {
		if fn(v) {
			return true
		}
	}
	return false
}

// Forall verifies that all elements of NumList return true for the passed func.
func (list NumList) Forall(fn func(Num) bool) bool {
	for _, v := range list {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Foreach iterates over NumList and executes the passed func against each element.
func (list NumList) Foreach(fn func(Num)) {
	for _, v := range list {
		fn(v)
	}
}

// Send gets a channel that will send all the elements in order.
func (list NumList) Send() <-chan Num {
	ch := make(chan Num)
	go func() {
		for _, v := range list {
			ch <- v
		}
		close(ch)
	}()
	return ch
}

// Reverse returns a copy of NumList with all elements in the reverse order.
func (list NumList) Reverse() NumList {
	numItems := len(list)
	result := make(NumList, numItems)
	last := numItems - 1
	for i, v := range list {
		result[last-i] = v
	}
	return result
}

// Shuffle returns a shuffled copy of NumList, using a version of the Fisher-Yates shuffle.
func (list NumList) Shuffle() NumList {
	numItems := len(list)
	result := make(NumList, numItems)
	copy(result, list)
	for i := 0; i < numItems; i++ {
		r := i + rand.Intn(numItems-i)
		result.Swap(i, r)
	}
	return result
}

//-------------------------------------------------------------------------------------------------

// Take returns a new NumList containing the leading n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list NumList) Take(n int) NumList {
	if n > len(list) {
		return list
	} else {
		return list[0:n]
	}
}

// Drop returns a new NumList without the leading n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list NumList) Drop(n int) NumList {
	l := len(list)
	if n > l {
		return list[l:]
	} else {
		return list[n:]
	}
}

// TakeLast returns a new NumList containing the trailing n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list NumList) TakeLast(n int) NumList {
	l := len(list)
	if n > l {
		return list
	} else {
		return list[l-n:]
	}
}

// DropLast returns a new NumList without the trailing n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list NumList) DropLast(n int) NumList {
	l := len(list)
	if n > l {
		return list[l:]
	} else {
		return list[0 : l-n]
	}
}

// TakeWhile returns a new NumList containing the leading elements of the source list. Whilst the
// predicate p returns true, elements are added to the result. Once predicate p returns false, all remaining
// elemense are excluded.
func (list NumList) TakeWhile(p func(Num) bool) (result NumList) {
	for _, v := range list {
		if p(v) {
			result = append(result, v)
		} else {
			return
		}
	}
	return
}

// DropWhile returns a new NumList containing the trailing elements of the source list. Whilst the
// predicate p returns true, elements are excluded from the result. Once predicate p returns false, all remaining
// elemense are added.
func (list NumList) DropWhile(p func(Num) bool) (result NumList) {
	adding := false
	for _, v := range list {
		if !p(v) || adding {
			adding = true
			result = append(result, v)
		}
	}
	return
}

//-------------------------------------------------------------------------------------------------

// Filter returns a new NumList whose elements return true for func.
func (list NumList) Filter(fn func(Num) bool) NumCollection {
	result := make(NumList, 0, len(list)/2)
	for _, v := range list {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Partition returns two new NumLists whose elements return true or false for the predicate, p.
// The first result consists of all elements that satisfy the predicate and the second result consists of
// all elements that don't. The relative order of the elements in the results is the same as in the
// original list.
func (list NumList) Partition(p func(Num) bool) (NumCollection, NumCollection) {
	matching := make(NumList, 0, len(list)/2)
	others := make(NumList, 0, len(list)/2)
	for _, v := range list {
		if p(v) {
			matching = append(matching, v)
		} else {
			others = append(others, v)
		}
	}
	return matching, others
}

// CountBy gives the number elements of NumList that return true for the passed predicate.
func (list NumList) CountBy(predicate func(Num) bool) (result int) {
	for _, v := range list {
		if predicate(v) {
			result++
		}
	}
	return
}

// MinBy returns an element of NumList containing the minimum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such
// element is returned. Panics if there are no elements.
func (list NumList) MinBy(less func(Num, Num) bool) (result Num) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the minimum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// MaxBy returns an element of NumList containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such
// element is returned. Panics if there are no elements.
func (list NumList) MaxBy(less func(Num, Num) bool) (result Num) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the maximum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if list[i] != list[m] && !less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// DistinctBy returns a new NumList whose elements are unique, where equality is defined by a passed func.
func (list NumList) DistinctBy(equal func(Num, Num) bool) (result NumList) {
Outer:
	for _, v := range list {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

// IndexWhere finds the index of the first element satisfying some predicate. If none exists, -1 is returned.
func (list NumList) IndexWhere(p func(Num) bool) int {
	for i, v := range list {
		if p(v) {
			return i
		}
	}
	return -1
}

// IndexWhere2 finds the index of the first element satisfying some predicate at or after some start index.
// If none exists, -1 is returned.
func (list NumList) IndexWhere2(p func(Num) bool, from int) int {
	for i, v := range list {
		if i >= from && p(v) {
			return i
		}
	}
	return -1
}

// LastIndexWhere finds the index of the last element satisfying some predicate.
// If none exists, -1 is returned.
func (list NumList) LastIndexWhere(p func(Num) bool) int {
	for i := len(list) - 1; i >= 0; i-- {
		v := list[i]
		if p(v) {
			return i
		}
	}
	return -1
}

// LastIndexWhere2 finds the index of the last element satisfying some predicate at or after some start index.
// If none exists, -1 is returned.
func (list NumList) LastIndexWhere2(p func(Num) bool, before int) int {
	for i := len(list) - 1; i >= 0; i-- {
		v := list[i]
		if i <= before && p(v) {
			return i
		}
	}
	return -1
}

// Equals verifies that another NumCollection has the same size and elements as this one. Also,
// because this collection is a sequence, the order must be the same.
// Omitted if Num is not comparable.
func (list NumList) Equals(other NumCollection) bool {
	if len(list) != other.Size() {
		return false
	}
	eq := true
	i := 0
	other.Foreach(func(a Num) {
		if eq {
			v := list[i]
			if v != a {
				eq = false
			}
			i++
		}
	})
	return eq
}

//-------------------------------------------------------------------------------------------------
// These methods are provided because Num is comparable.

// IndexOf finds the index of the first element specified. If none exists, -1 is returned.
func (list NumList) IndexOf(value Num) int {
	for i, v := range list {
		if v == value {
			return i
		}
	}
	return -1
}

// IndexOf2 finds the index of the first element specified at or after some start index.
// If none exists, -1 is returned.
func (list NumList) IndexOf2(value Num, from int) int {
	for i, v := range list {
		if i >= from && v == value {
			return i
		}
	}
	return -1
}

// Contains verifies that a given value is contained in NumList.
func (list NumList) Contains(value Num) bool {
	for _, v := range list {
		if v == value {
			return true
		}
	}
	return false
}

// Count gives the number elements of NumList that match a certain value.
func (list NumList) Count(value Num) (result int) {
	for _, v := range list {
		if v == value {
			result++
		}
	}
	return
}

// Distinct returns a new NumList whose elements are unique, retaining the original order.
func (list NumList) Distinct() NumCollection {
	result := make(NumList, 0)
	appended := make(map[Num]bool)
	for _, v := range list {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

//-------------------------------------------------------------------------------------------------
// These methods are provided because Num is numeric.

// Sum sums all elements in the list.
func (list NumList) Sum() (result Num) {
	for _, v := range list {
		result += v
	}
	return
}

// Mean computes the arithmetic mean of all elements.
// Panics if the list is empty.
func (list NumList) Mean() float64 {
	l := len(list)
	if l == 0 {
		panic("Cannot compute the arithmetic mean of zero-length NumList")
	}
	sum := list.Sum()
	return float64(sum) / float64(l)
}

//-------------------------------------------------------------------------------------------------
// These methods are provided because Num is ordered.

// Min returns the element with the minimum value. In the case of multiple items being equally minimal,
// the first such element is returned. Panics if the collection is empty.
func (list NumList) Min() (result Num) {
	if len(list) == 0 {
		panic("Cannot determine the Min of an empty list.")
	}
	result = list[0]
	for _, v := range list {
		if v < result {
			result = v
		}
	}
	return
}

// Max returns the element with the maximum value. In the case of multiple items being equally maximal,
// the first such element is returned. Panics if the collection is empty.
func (list NumList) Max() (result Num) {
	if len(list) == 0 {
		panic("Cannot determine the Max of an empty list.")
	}
	result = list[0]
	for _, v := range list {
		if v > result {
			result = v
		}
	}
	return
}

//-------------------------------------------------------------------------------------------------

// String implements the Stringer interface to render the list as a comma-separated string enclosed in square brackets.
func (list NumList) String() string {
	return list.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string using a supplied separator. No enclosing marks are added.
func (list NumList) MkString(sep string) string {
	return list.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string, using the prefix, separator and suffix supplied.
func (list NumList) MkString3(pfx, mid, sfx string) string {
	b := bytes.Buffer{}
	b.WriteString(pfx)
	l := len(list)
	if l > 0 {
		v := list[0]
		b.WriteString(fmt.Sprintf("%v", v))
		for i := 1; i < l; i++ {
			v := list[i]
			b.WriteString(mid)
			b.WriteString(fmt.Sprintf("%v", v))
		}
	}
	b.WriteString(sfx)
	return b.String()
}

//-------------------------------------------------------------------------------------------------
// Methods to interface lists with options.

// First returns the first element that returns true for the passed func. Returns none if no elements return true.
func (list NumList) Find(fn func(Num) bool) OptionalNum {
	for _, v := range list {
		if fn(v) {
			//return SomeNum(v)
		}
	}
	return NoNum()
}

// HeadOption gets the first item in the list, provided there is one.
func (list NumList) HeadOption() OptionalNum {
	l := len(list)
	if l > 0 {
		return SomeNum(list[0])
	} else {
		return NoNum()
	}
}

// TailOption gets the last item in the list, provided there is one.
func (list NumList) LastOption() OptionalNum {
	l := len(list)
	if l > 0 {
		return SomeNum(list[l-1])
	} else {
		return NoNum()
	}
}

//-------------------------------------------------------------------------------------------------

// OptionalNum is an optional of type Num. Use it where you want to be explicit about
// the presence or absence of data.
//
// Optional values follow a similar pattern to Scala Options. In particular, an option is a collection
// with a maximum cardinality of one. As such, options can be converted to/from lists and sets.
// See e.g. http://www.scala-lang.org/api/2.11.7/index.html#scala.Option
type OptionalNum struct {
	x *Num
}

// shared none value
var noneNum = OptionalNum{nil}

// NoNum gets an empty instance.
func NoNum() OptionalNum {
	return noneNum
}

// SomeNum gets a non-empty instance wrapping some value *x*.
func SomeNum(x Num) OptionalNum {

	return OptionalNum{&x}

}

//-------------------------------------------------------------------------------------------------

// panics if option is empty
func (o OptionalNum) Head() Num {
	return o.Get()
}

func (o OptionalNum) Get() Num {
	if o.IsEmpty() {
		panic("Attempt to access non-existent value")
	}
	return *o.x
}

func (o OptionalNum) GetOrElse(d func() Num) Num {
	if o.IsEmpty() {
		return d()
	}
	return *o.x
}

func (o OptionalNum) OrElse(alternative func() OptionalNum) OptionalNum {
	if o.IsEmpty() {
		return alternative()
	}
	return o
}

//-------------------------------------------------------------------------------------------------

func (o OptionalNum) Size() int {
	if o.IsEmpty() {
		return 0
	}
	return 1
}

func (o OptionalNum) Len() int {
	return o.Size()
}

func (o OptionalNum) IsEmpty() bool {
	return o.x == nil
}

func (o OptionalNum) NonEmpty() bool {
	return o.x != nil
}

// IsSequence returns false for options.
func (o OptionalNum) IsSequence() bool {
	return false
}

// IsSet returns false for options.
func (o OptionalNum) IsSet() bool {
	return false
}

// IsDefined returns true if the option is defined, i.e. non-empty. This is an alias for NonEmpty().
func (o OptionalNum) IsDefined() bool {
	return o.NonEmpty()
}

//-------------------------------------------------------------------------------------------------

func (o OptionalNum) Find(predicate func(Num) bool) OptionalNum {
	if o.IsEmpty() {
		return o
	}
	if predicate(*o.x) {
		return o
	}
	return noneNum
}

func (o OptionalNum) Exists(predicate func(Num) bool) bool {
	if o.IsEmpty() {
		return false
	}
	return predicate(*o.x)
}

func (o OptionalNum) Forall(predicate func(Num) bool) bool {
	if o.IsEmpty() {
		return true
	}
	return predicate(*o.x)
}

func (o OptionalNum) Foreach(fn func(Num)) {
	if o.NonEmpty() {
		fn(*o.x)
	}
}

// Send gets a channel that will send all the elements in order.
func (o OptionalNum) Send() <-chan Num {
	ch := make(chan Num)
	go func() {
		if o.NonEmpty() {
			ch <- *o.x
		}
		close(ch)
	}()
	return ch
}

func (o OptionalNum) Filter(predicate func(Num) bool) NumCollection {
	return o.Find(predicate)
}

func (o OptionalNum) Partition(predicate func(Num) bool) (NumCollection, NumCollection) {
	if o.IsEmpty() {
		return o, o
	}
	if predicate(*o.x) {
		return o, noneNum
	}
	return noneNum, o
}

func (o OptionalNum) ToSlice() []Num {
	slice := make([]Num, o.Size())
	if o.NonEmpty() {
		slice[0] = *o.x
	}
	return slice
}

// ToInts gets all the elements in a []int.
func (o OptionalNum) ToInts() []int {
	slice := make([]int, o.Size())
	if o.NonEmpty() {
		slice[0] = int(*o.x)
	}
	return slice
}

// ToList gets the option's element in a NumList.
func (o OptionalNum) ToList() NumList {
	return NumList(o.ToSlice())
}

// ToSet gets the option's element in a NumSet.
func (o OptionalNum) ToSet() NumSet {
	return NewNumSet(o.ToSlice()...)
}

//-------------------------------------------------------------------------------------------------
// These methods require Num be comparable.

// Equals verifies that one or more elements of NumList return true for the passed func.
func (o OptionalNum) Equals(other NumCollection) bool {
	if o.IsEmpty() {
		return other.IsEmpty()
	}
	if other.IsEmpty() || other.Size() > 1 {
		return false
	}
	a := o.x
	s := other.ToSlice()
	b := s[0]
	return *a == b
}

func (o OptionalNum) Contains(value Num) bool {
	if o.IsEmpty() {
		return false
	}
	return *(o.x) == value
}

func (o OptionalNum) Count(value Num) int {
	if o.Contains(value) {
		return 1
	}
	return 0
}

// Distinct returns a new NumCollection whose elements are all unique. For options, this simply returns the
// receiver.
// Omitted if Num is not comparable.
func (o OptionalNum) Distinct() NumCollection {
	return o
}

// Min returns the minimum value of NumList. In the case of multiple items being equally minimal,
// the first such element is returned. Panics if the collection is empty.
func (o OptionalNum) Min() Num {
	return o.Get()
}

// Max returns the maximum value of NumList. In the case of multiple items being equally maximal,
// the first such element is returned. Panics if the collection is empty.
func (o OptionalNum) Max() Num {
	return o.Get()
}

//-------------------------------------------------------------------------------------------------

// Sum sums Num elements.
// Omitted if Num is not numeric.
func (o OptionalNum) Sum() Num {

	if o.IsEmpty() {
		return 0
	}
	return *(o.x)

}

// Mean computes the arithmetic mean of all elements.
// Panics if the list is empty.
func (o OptionalNum) Mean() float64 {
	if o.IsEmpty() {
		panic("Cannot compute the arithmetic mean of zero-length OptionalNum")
	}
	return float64(*(o.x))
}

//-------------------------------------------------------------------------------------------------

// String implements the Stringer interface to render the option as an array of one element.
func (o OptionalNum) String() string {
	return o.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string.
func (o OptionalNum) MkString(sep string) string {
	return o.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string.
func (o OptionalNum) MkString3(pfx, mid, sfx string) string {
	if o.IsEmpty() {
		return fmt.Sprintf("%s%s", pfx, sfx)
	}
	return fmt.Sprintf("%s%v%s", pfx, *(o.x), sfx)
}

//-------------------------------------------------------------------------------------------------

// NumSet is a typesafe set of Num items.
// The implementation is based on an underyling Go map, which can be manipulated directly,
// but otherwise instances are essentially immutable.
// The set-agebra functions *Union*, *Intersection* and *Difference* allow new variants to be constructed
// easily; these methods do not modify the input sets.
type NumSet map[Num]struct{}

//-------------------------------------------------------------------------------------------------

// NewNumSet constructs a new set containing the supplied values, if any.
func NewNumSet(values ...Num) NumSet {
	set := make(map[Num]struct{})
	for _, v := range values {
		set[v] = struct{}{}
	}
	return NumSet(set)
}

// BuildNumSetFrom constructs a new NumSet from a channel that supplies a stream of values
// until it is closed. The function returns all these values in a set (i.e. without any duplicates).
func BuildNumSetFrom(source <-chan Num) NumSet {
	set := make(map[Num]struct{})
	for v := range source {
		set[v] = struct{}{}
	}
	return NumSet(set)
}

//-------------------------------------------------------------------------------------------------

// IsSequence returns false for sets.
func (set NumSet) IsSequence() bool {
	return false
}

// IsSet returns true for sets.
func (set NumSet) IsSet() bool {
	return true
}

func (set NumSet) Size() int {
	return len(set)
}

func (set NumSet) IsEmpty() bool {
	return len(set) == 0
}

func (set NumSet) NonEmpty() bool {
	return len(set) > 0
}

// Head gets an arbitrary element.
func (set NumSet) Head() Num {
	for v := range set {
		return v
	}
	panic("Set is empty")
}

// ToSlice gets all the set's elements in a plain slice.
func (set NumSet) ToSlice() []Num {
	slice := make([]Num, set.Size())
	i := 0
	for v := range set {
		slice[i] = v
		i++
	}
	return slice
}

// ToInts gets all the elements in a []int.
func (set NumSet) ToInts() []int {
	slice := make([]int, len(set))
	i := 0
	for v := range set {
		slice[i] = int(v)
		i++
	}
	return slice
}

// ToList gets all the set's elements in a in SetList.
func (set NumSet) ToList() NumList {
	return NumList(set.ToSlice())
}

// ToSet gets the current set, which requires no further conversion.
func (set NumSet) ToSet() NumSet {
	return set
}

// Contains tests whether an item is already in the NumSet.
func (set NumSet) Contains(i Num) bool {
	_, found := set[i]
	return found
}

// ContainsAll tests whether many items are all in the NumSet.
func (set NumSet) ContainsAll(i ...Num) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

func (set NumSet) actualSubset(other NumSet) bool {
	for item := range set {
		if !other.Contains(item) {
			return false
		}
	}
	return true
}

// Equals determines if two sets are equal to each other.
// They are considered equal if both are the same size and both have the same items.
func (set NumSet) Equals(other NumCollection) bool {
	otherSet, isSet := other.(NumSet)
	return isSet && set.Size() == other.Size() && set.actualSubset(otherSet)
}

// IsSubset determines if every item in the other set is in this set.
func (set NumSet) IsSubset(other NumSet) bool {
	return set.Size() <= other.Size() && set.actualSubset(other)
}

// IsProperSubset determines if every item in the other set is in this set and this set is
// smaller than the other.
func (set NumSet) IsProperSubset(other NumSet) bool {
	return set.Size() < other.Size() && set.actualSubset(other)
}

// IsSuperset determines if every item of this set is in the other set.
func (set NumSet) IsSuperset(other NumSet) bool {
	return other.IsSubset(set)
}

// Union returns a new set with all items in both sets.
func (set NumSet) Union(other NumSet) NumSet {
	union := NewNumSet()
	for item := range set {
		union[item] = struct{}{}
	}
	for item := range other {
		union[item] = struct{}{}
	}
	return union
}

// Intersection returns a new set with items that exist only in both sets.
func (set NumSet) Intersection(other NumSet) NumSet {
	intersection := NewNumSet()
	// loop over the smaller set
	if set.Size() < other.Size() {
		for item := range set {
			if other.Contains(item) {
				intersection[item] = struct{}{}
			}
		}
	} else {
		for item := range other {
			if set.Contains(item) {
				intersection[item] = struct{}{}
			}
		}
	}
	return intersection
}

// Difference returns a new set with items in the current set but not in the other set
func (set NumSet) Difference(other NumSet) NumSet {
	diffs := NewNumSet()
	for item := range set {
		if !other.Contains(item) {
			diffs[item] = struct{}{}
		}
	}
	return diffs
}

// Add creates a new set with elements added. This is similar to Union, but takes a slice of extra values.
// The receiver is not modified.
func (set NumSet) Add(others ...Num) NumSet {
	added := NewNumSet()
	for item := range set {
		added[item] = struct{}{}
	}
	for _, item := range others {
		added[item] = struct{}{}
	}
	return added
}

// Remove creates a new set with elements removed. This is similar to Difference, but takes a slice of unwanted values.
// The receiver is not modified.
func (set NumSet) Remove(unwanted ...Num) NumSet {
	removed := NewNumSet()
	for item := range set {
		removed[item] = struct{}{}
	}
	for _, item := range unwanted {
		delete(removed, item)
	}
	return removed
}

// Exists verifies that one or more elements of NumSet return true for the passed func.
func (set NumSet) Exists(fn func(Num) bool) bool {
	for v := range set {
		if fn(v) {
			return true
		}
	}
	return false
}

// Forall verifies that all elements of NumSet return true for the passed func.
func (set NumSet) Forall(fn func(Num) bool) bool {
	for v := range set {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Foreach iterates over NumSet and executes the passed func against each element.
// The order of the elements is not well defined but is probably repeatably stable until the set is changed.
func (set NumSet) Foreach(fn func(Num)) {
	for v := range set {
		fn(v)
	}
}

// Send sends all elements along a channel of type Num.
// The order of the elements is not well defined but is probably repeatably stable until the set is changed.
func (set NumSet) Send() <-chan Num {
	ch := make(chan Num)
	go func() {
		for v := range set {
			ch <- v
		}
		close(ch)
	}()
	return ch
}

// Filter returns a new NumSet whose elements return true for func.
func (set NumSet) Filter(fn func(Num) bool) NumCollection {
	result := make(map[Num]struct{})
	for v := range set {
		if fn(v) {
			result[v] = struct{}{}
		}
	}
	return NumSet(result)
}

// Partition returns two new NumLists whose elements return true or false for the predicate, p.
// The first result consists of all elements that satisfy the predicate and the second result consists of
// all elements that don't. The relative order of the elements in the results is the same as in the
// original set.
func (set NumSet) Partition(p func(Num) bool) (NumCollection, NumCollection) {
	matching := make(map[Num]struct{})
	others := make(map[Num]struct{})
	for v := range set {
		if p(v) {
			matching[v] = struct{}{}
		} else {
			others[v] = struct{}{}
		}
	}
	return NumSet(matching), NumSet(others)
}

// CountBy gives the number elements of NumSet that return true for the passed predicate.
func (set NumSet) CountBy(predicate func(Num) bool) (result int) {
	for v := range set {
		if predicate(v) {
			result++
		}
	}
	return
}

// MinBy returns an element of NumSet containing the minimum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such
// element is returned. Panics if there are no elements.
func (set NumSet) MinBy(less func(Num, Num) bool) (result Num) {
	l := len(set)
	if l == 0 {
		panic("Cannot determine the minimum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if less(v, result) {
			result = v
		}
	}
	return
}

// MaxBy returns an element of NumSet containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such
// element is returned. Panics if there are no elements.
func (set NumSet) MaxBy(less func(Num, Num) bool) (result Num) {
	l := len(set)
	if l == 0 {
		panic("Cannot determine the maximum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if less(result, v) {
			result = v
		}
	}
	return
}

// These methods require Num be numeric.

// Sum sums all elements in the set.
func (set NumSet) Sum() (result Num) {
	for v := range set {
		result += v
	}
	return
}

// Mean computes the arithmetic mean of all elements.
// Panics if the set is empty.
func (set NumSet) Mean() float64 {
	l := len(set)
	if l == 0 {
		panic("Cannot compute the arithmetic mean of zero-length NumSet")
	}
	sum := set.Sum()
	return float64(sum) / float64(l)
}

//-------------------------------------------------------------------------------------------------
// These methods require Num be ordered.

// Min returns the element with the minimum value. In the case of multiple items being equally minimal,
// any such element is returned. Panics if the collection is empty.
func (set NumSet) Min() (result Num) {
	if len(set) == 0 {
		panic("Cannot determine the minimum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if v < result {
			result = v
		}
	}
	return
}

// Max returns the element with the maximum value. In the case of multiple items being equally maximal,
// any such element is returned. Panics if the collection is empty.
func (set NumSet) Max() (result Num) {
	if len(set) == 0 {
		panic("Cannot determine the maximum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if v > result {
			result = v
		}
	}
	return
}

// String implements the Stringer interface to render the set as a comma-separated array.
func (set NumSet) String() string {
	return set.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string.
func (set NumSet) MkString(sep string) string {
	return set.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string.
func (set NumSet) MkString3(pfx, mid, sfx string) string {
	b := bytes.Buffer{}
	b.WriteString(pfx)
	l := len(set)
	if l > 0 {
		sep := ""
		for v := range set {
			b.WriteString(sep)
			b.WriteString(fmt.Sprintf("%v", v))
			sep = mid
		}
	}
	b.WriteString(sfx)
	return b.String()
}

//-------------------------------------------------------------------------------------------------

// This plumbing suite provides standard functions for piping data between goroutines.
// All these functions run until the input channel is closed (or all input channels are closed, if
// multiple). They then close their output channel(s).
// None of these functions create a goroutine - this must be done at the call site.

//-------------------------------------------------------------------------------------------------

// NumGenerator produces a stream of Num based on a supplied generator function.
// The function fn is invoked N times with the integers from 0 to N-1. Each result is sent out.
// Finally, the output channel is closed and the generator terminates.
//
// It is part of the Plumbing function suite for Num.
func NumGenerator(out chan<- Num, iterations int, fn func(int) Num) {
	NumGenerator3(out, 0, iterations-1, 1, fn)
}

// NumGenerator produces a stream of Num based on a supplied generator function.
// The function fn is invoked *(|to - from|) / |stride|* times with the integers in the range specified by
// from, to and stride. If stride is negative, from should be greater than to.
// For each iteration, the computed function result is sent out.
// If stride is zero, the loop never terminates. Otherwise, after the generator has reached the
// loop end, the output channel is closed and the generator terminates.
//
// It is part of the Plumbing function suite for Num.
func NumGenerator3(out chan<- Num, from, to, stride int, fn func(int) Num) {
	if (from > to && stride > 0) || (from < to && stride < 0) {
		panic("Loop conditions are divergent.")
	}
	if from > to && stride < 0 {
		for i := from; i >= to; i += stride {
			out <- fn(i)
		}
	} else {
		for i := from; i <= to; i += stride {
			out <- fn(i)
		}
	}
	close(out)
}

// NumDelta duplicates a stream of Num to two output channels.
// When the sender closes the input channel, both output channels are closed then the function terminates.
//
// It is part of the Plumbing function suite for Num.
func NumDelta(in <-chan Num, out1, out2 chan<- Num) {
	for v := range in {
		select {
		case out1 <- v:
			out2 <- v
		case out2 <- v:
			out1 <- v
		}
	}
	close(out1)
	close(out2)
}

// NumZip2 interleaves two streams of Num.
// Each input channel is used in turn, alternating between them.
// The function terminates when *both* input channels have been closed by their senders.
// The output channel is then closed also.
//
// It is part of the Plumbing function suite for Num.
func NumZip2(in1, in2 <-chan Num, out chan<- Num) {
	closed2 := false
	for v := range in1 {
		out <- v
		v, ok := <-in2
		if ok {
			out <- v
		} else {
			closed2 = true
		}
	}
	// need to drain in2 as well?
	if !closed2 {
		for _ = range in2 {
		}
	}
	close(out)
}

// NumMux2 multiplexes two streams of Num into a single output channel.
// Each input channel is used as soon as it is ready.
// When a signal is received from the closer channel, the output channel is then closed.
// Concurrently, both input channels are then passed into blackholes that comsume them until they too are closed,
// and the function terminates.
//
// It is part of the Plumbing function suite for Num.
func NumMux2(in1, in2 <-chan Num, closer <-chan bool, out chan<- Num) {
	running := true
	for running {
		select {
		case v := <-in1:
			out <- v
		case v := <-in2:
			out <- v
		case _ = <-closer:
			running = false
		}
	}
	go NumBlackHole(in1)
	go NumBlackHole(in2)
	close(out)
}

// NumBlackHole silently consumes a stream of Num.
// It terminates when the sender closes the channel.
//
// It is part of the Plumbing function suite for Num.
func NumBlackHole(in <-chan Num) {
	for _ = range in {
		// om nom nom
	}
}

// NumFilter filters a stream of Num, silently dropping elements that do not match the predicate p.
// When the sender closes the input channel, the output channel is closed then the function terminates.
//
// It is part of the Plumbing function suite for Num.
func NumFilter(in <-chan Num, out chan<- Num, p func(Num) bool) {
	for v := range in {
		if p(v) {
			out <- v
		}
	}
	close(out)
}

// NumPartition filters a stream of Num into two output streams using a predicate p, those that
// match and all others.
// When the sender closes the input channel, both output channels are closed then the function terminates.
//
// It is part of the Plumbing function suite for Num.
func NumPartition(in <-chan Num, matching, others chan<- Num, p func(Num) bool) {
	for v := range in {
		if p(v) {
			matching <- v
		} else {
			others <- v
		}
	}
	close(matching)
	close(others)
}

// NumMap transforms a stream of Num by applying a function fn to each item in the stream.
// When the sender closes the input channel, the output channel is closed then the function terminates.
//
// It is part of the Plumbing function suite for Num.
func NumMap(in <-chan Num, out chan<- Num, fn func(Num) Num) {
	for v := range in {
		out <- fn(v)
	}
	close(out)
}

// NumFlatMap transforms a stream of Num by applying a function fn to each item in the stream that
// gives zero or more results, all of which are sent out.
// When the sender closes the input channel, the output channel is closed then the function terminates.
//
// It is part of the Plumbing function suite for Num.
func NumFlatMap(in <-chan Num, out chan<- Num, fn func(Num) NumCollection) {
	for vi := range in {
		c := fn(vi)
		if c.NonEmpty() {
			for vo := range c.Send() {
				out <- vo
			}
		}
	}
	close(out)
}

//-------------------------------------------------------------------------------------------------
// List:MapTo[Foo]

// MapToFoo transforms NumList to FooList.
func (list NumList) MapToFoo(fn func(Num) Foo) FooCollection {
	result := make(FooList, 0, len(list))
	for _, v := range list {
		u := fn(v)
		result = append(result, u)
	}
	return result
}

// FlatMapToFoo transforms NumList to FooList, by repeatedly
// calling the supplied function and concatenating the results as a single flat list.
func (list NumList) FlatMapToFoo(fn func(Num) FooCollection) FooCollection {
	result := make(FooList, 0, len(list))
	for _, v := range list {
		u := fn(v)
		if u.NonEmpty() {
			result = append(result, (u.ToList())...)
		}
	}
	return result
}

//-------------------------------------------------------------------------------------------------
// List:With[Foo]

// FoldLeftFoo applies a binary operator to a start value and all elements of this list, going left to right.
func (list NumList) FoldLeftFoo(zero Foo, fn func(Foo, Num) Foo) Foo {
	sum := zero
	for _, v := range list {
		sum = fn(sum, v)
	}
	return sum
}

// FoldRightFoo applies a binary operator to a start value and all elements of this list, going right to left.
func (list NumList) FoldRightFoo(zero Foo, fn func(Foo, Num) Foo) Foo {
	sum := zero
	for i := len(list) - 1; i >= 0; i-- {
		sum = fn(sum, list[i])
	}
	return sum
}

// This methods require Num be comparable.

// GroupByFoo groups elements into a map keyed by Foo.
func (list NumList) GroupByFoo(fn func(Num) Foo) map[Foo]NumList {
	result := make(map[Foo]NumList)
	for _, v := range list {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// These methods require Foo be ordered.

// MinByFoo finds the first element which yields the smallest value measured by function fn.
// fn is usually called a projection or measuring function.
// Panics if there are no elements.
func (list NumList) MinByFoo(fn func(Num) Foo) (result Num) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the minimum of an empty list.")
		return
	}
	result = list[0]
	if l > 1 {
		min := fn(result)
		for i := 1; i < l; i++ {
			v := list[i]
			f := fn(v)
			if min > f {
				min = f
				result = v
			}
		}
	}
	return
}

// MaxByFoo finds the first element which yields the largest value measured by function fn.
// fn is usually called a projection or measuring function.
// Panics if there are no elements.
func (list NumList) MaxByFoo(fn func(Num) Foo) (result Num) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the maximum of an empty list.")
	}
	result = list[0]
	if l > 1 {
		max := fn(result)
		for i := 1; i < l; i++ {
			v := list[i]
			f := fn(v)
			if max < f {
				max = f
				result = v
			}
		}
	}
	return
}

// List flags: {Collection:false List:true Option:true Set:true Plumbing:false Tag:map[Plumbing:true MapTo:true With:true]}
