// Generated by: setup
// TypeWriter: slice
// Directive: +test on Thing

package main

import (
	"errors"
	"math/rand"
)

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

// ThingList is a slice of type Thing. Use it where you would use []Thing.
type ThingList []Thing

// Len returns the number of items in the slice.
// There is no Size() method; use Len() instead.
// This is one of the three methods in the standard sort.Interface.
func (rcv ThingList) Len() int {
	return len(rcv)
}

// Swap exchanges two elements, which is neceessary during sorting etc.
// This is one of the three methods in the standard sort.Interface.
func (rcv ThingList) Swap(i, j int) {
	rcv[i], rcv[j] = rcv[j], rcv[i]
}

// IsEmpty tests whether ThingList is empty.
func (slice ThingList) IsEmpty() bool {
	return len(slice) == 0
}

// NonEmpty tests whether ThingList is empty.
func (slice ThingList) NonEmpty() bool {
	return len(slice) > 0
}

// Exists verifies that one or more elements of ThingList return true for the passed func.
func (slice ThingList) Exists(fn func(Thing) bool) bool {
	for _, v := range slice {
		if fn(v) {
			return true
		}
	}
	return false
}

// Forall verifies that all elements of ThingList return true for the passed func.
func (slice ThingList) Forall(fn func(Thing) bool) bool {
	for _, v := range slice {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Foreach iterates over ThingList and executes the passed func against each element.
func (slice ThingList) Foreach(fn func(Thing)) {
	for _, v := range slice {
		fn(v)
	}
}

// Filter returns a new ThingList whose elements return true for func.
func (rcv ThingList) Filter(fn func(Thing) bool) (result ThingList) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Partition returns two new ThingLists whose elements return true or false for the predicate, p.
// The first result consists of all elements that satisfy the predicate and the second result consists of
// all elements that don't. The relative order of the elements in the results is the same as in the
// original slice.
func (slice ThingList) Partition(p func(Thing) bool) (matching ThingList, others ThingList) {
	for _, v := range slice {
		if p(v) {
			matching = append(matching, v)
		} else {
			others = append(others, v)
		}
	}
	return
}

// Take returns a new ThingList containing the leading n elements of the source slice.
// If n is greater than the size of the slice, the whole slice is returned.
func (slice ThingList) Take(n int) ThingList {
	if n > len(slice) {
		return slice
	} else {
		return slice[0:n]
	}
}

// Drop returns a new ThingList without the leading n elements of the source slice.
// If n is greater than the size of the slice, the whole slice is returned.
func (slice ThingList) Drop(n int) ThingList {
	l := len(slice)
	if n > l {
		return slice[l:]
	} else {
		return slice[n:]
	}
}

// TakeLast returns a new ThingList containing the trailing n elements of the source slice.
// If n is greater than the size of the slice, the whole slice is returned.
func (slice ThingList) TakeLast(n int) ThingList {
	l := len(slice)
	if n > l {
		return slice
	} else {
		return slice[l-n:]
	}
}

// DropLast returns a new ThingList without the trailing n elements of the source slice.
// If n is greater than the size of the slice, the whole slice is returned.
func (slice ThingList) DropLast(n int) ThingList {
	l := len(slice)
	if n > l {
		return slice[l:]
	} else {
		return slice[0 : l-n]
	}
}

// TakeWhile returns a new ThingList containing the leading elements of the source slice. Whilst the
// predicate p returns true, elements are added to the result. Once predicate p returns false, all remaining
// elemense are excluded.
func (slice ThingList) TakeWhile(p func(Thing) bool) (result ThingList) {
	for _, v := range slice {
		if p(v) {
			result = append(result, v)
		} else {
			return
		}
	}
	return
}

// DropWhile returns a new ThingList containing the trailing elements of the source slice. Whilst the
// predicate p returns true, elements are excluded from the result. Once predicate p returns false, all remaining
// elemense are added.
func (slice ThingList) DropWhile(p func(Thing) bool) (result ThingList) {
	adding := false
	for _, v := range slice {
		if !p(v) || adding {
			adding = true
			result = append(result, v)
		}
	}
	return
}

// Reverse returns a copy of ThingList with all elements in the reverse order.
func (rcv ThingList) Reverse() ThingList {
	numItems := len(rcv)
	result := make(ThingList, numItems)
	last := numItems - 1
	for i, v := range rcv {
		result[last-i] = v
	}
	return result
}

// Shuffle returns a shuffled copy of ThingList, using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (rcv ThingList) Shuffle() ThingList {
	numItems := len(rcv)
	result := make(ThingList, numItems)
	copy(result, rcv)
	for i := 0; i < numItems; i++ {
		r := i + rand.Intn(numItems-i)
		result.Swap(i, r)
	}
	return result
}

// CountBy gives the number elements of ThingList that return true for the passed predicate.
func (rcv ThingList) CountBy(predicate func(Thing) bool) (result int) {
	for _, v := range rcv {
		if predicate(v) {
			result++
		}
	}
	return
}

// MinBy returns an element of ThingList containing the minimum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such
// element is returned. Returns error if no elements.
func (rcv ThingList) MinBy(less func(Thing, Thing) bool) (result Thing, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("Cannot determine the MinBy of an empty slice.")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// MaxBy returns an element of ThingList containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such
// element is returned. Returns error if no elements.
func (rcv ThingList) MaxBy(less func(Thing, Thing) bool) (result Thing, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("Cannot determine the MaxBy of an empty slice.")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// DistinctBy returns a new ThingList whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv ThingList) DistinctBy(equal func(Thing, Thing) bool) (result ThingList) {
Outer:
	for _, v := range rcv {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

// Min returns an element of ThingList containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (rcv ThingList) Min(less func(Thing, Thing) bool) (result Thing, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("Cannot determine the Min of an empty slice.")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// Max returns an element of ThingList containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such
// element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (rcv ThingList) Max(less func(Thing, Thing) bool) (result Thing, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("Cannot determine the Max of an empty slice.")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// Contains verifies that a given value is contained in ThingList.
func (slice ThingList) Contains(value Thing) bool {
	for _, v := range slice {
		if v == value {
			return true
		}
	}
	return false
}

// Count gives the number elements of ThingList that match a certain value.
func (rcv ThingList) Count(value Thing) (result int) {
	for _, v := range rcv {
		if v == value {
			result++
		}
	}
	return
}

// Distinct returns a new ThingList whose elements are unique. See: http://clipperhouse.github.io/gen/#Distinct
func (rcv ThingList) Distinct() (result ThingList) {
	appended := make(map[Thing]bool)
	for _, v := range rcv {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

// GroupByOther groups elements into a map keyed by Other. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv ThingList) GroupByOther(fn func(Thing) Other) map[Other]ThingList {
	result := make(map[Other]ThingList)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// MinOther selects the least value of Other in ThingList.
// Returns error on ThingList with no elements. See: http://clipperhouse.github.io/gen/#MinCustom
func (rcv ThingList) MinOther(fn func(Thing) Other) (result Other, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine Min of zero-length ThingList")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f < result {
				result = f
			}
		}
	}
	return
}

// MaxOther selects the largest value of Other in ThingList.
// Returns error on ThingList with no elements. See: http://clipperhouse.github.io/gen/#MaxCustom
func (rcv ThingList) MaxOther(fn func(Thing) Other) (result Other, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine Max of zero-length ThingList")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f > result {
				result = f
			}
		}
	}
	return
}

// SumOther sums Thing over elements in ThingList. See: http://clipperhouse.github.io/gen/#Sum
func (rcv ThingList) SumOther(fn func(Thing) Other) (result Other) {
	for _, v := range rcv {
		result += fn(v)
	}
	return
}

// MeanOther sums Other over all elements and divides by len(ThingList). See: http://clipperhouse.github.io/gen/#Mean
func (rcv ThingList) MeanOther(fn func(Thing) Other) (result Other, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine Mean[Other] of zero-length ThingList")
		return
	}
	for _, v := range rcv {
		result += fn(v)
	}
	result = result / Other(l)
	return
}

// AggregateOther iterates over ThingList, operating on each element while maintaining ‘state’. See: http://clipperhouse.github.io/gen/#Aggregate
func (rcv ThingList) AggregateOther(fn func(Other, Thing) Other) (result Other) {
	for _, v := range rcv {
		result = fn(result, v)
	}
	return
}

// MapToOther transforms a slice of Other from ThingList.
func (rcv ThingList) MapToOther(fn func(Thing) Other) (result OtherList) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv ThingList) First(fn func(Thing) bool) (result Thing, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no ThingList elements return true for passed func")
	return
}

// SortWith returns a new ordered ThingList, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv ThingList) SortWith(less func(Thing, Thing) bool) ThingList {
	result := make(ThingList, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortThingList(result, less, 0, n, maxDepth)
	return result
}

// IsSortedWith reports whether an instance of ThingList is sorted, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv ThingList) IsSortedWith(less func(Thing, Thing) bool) bool {
	n := len(rcv)
	for i := n - 1; i > 0; i-- {
		if less(rcv[i], rcv[i-1]) {
			return false
		}
	}
	return true
}

// SortWithDesc returns a new, descending-ordered ThingList, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv ThingList) SortWithDesc(less func(Thing, Thing) bool) ThingList {
	greater := func(a, b Thing) bool {
		return less(b, a)
	}
	return rcv.SortWith(greater)
}

// IsSortedDesc reports whether an instance of ThingList is sorted in descending order, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv ThingList) IsSortedWithDesc(less func(Thing, Thing) bool) bool {
	greater := func(a, b Thing) bool {
		return less(b, a)
	}
	return rcv.IsSortedWith(greater)
}

//-------------------------------------------------------------------------------------------------
// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapThingList(rcv ThingList, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortThingList(rcv ThingList, less func(Thing, Thing) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapThingList(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownThingList(rcv ThingList, less func(Thing, Thing) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapThingList(rcv, first+root, first+child)
		root = child
	}
}

func heapSortThingList(rcv ThingList, less func(Thing, Thing) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownThingList(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapThingList(rcv, first, first+i)
		siftDownThingList(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeThingList(rcv ThingList, less func(Thing, Thing) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapThingList(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapThingList(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapThingList(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeThingList(rcv ThingList, a, b, n int) {
	for i := 0; i < n; i++ {
		swapThingList(rcv, a+i, b+i)
	}
}

func doPivotThingList(rcv ThingList, less func(Thing, Thing) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeThingList(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeThingList(rcv, less, m, m-s, m+s)
		medianOfThreeThingList(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeThingList(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapThingList(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapThingList(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapThingList(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeThingList(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeThingList(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortThingList(rcv ThingList, less func(Thing, Thing) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortThingList(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotThingList(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortThingList(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortThingList(rcv, mhi, b)
		} else {
			quickSortThingList(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortThingList(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortThingList(rcv, less, a, b)
	}
}
