// Generated by: setup
// TypeWriter: List
// Directive: +test on Num1

package main

import (
	"bytes"
	"fmt"
	"math/rand"
	"sort"
)

//-------------------------------------------------------------------------------------------------

// Num1Collection is an interface for collections of type Num1, including sets, lists and options (where present).
type Num1Collection interface {
	// Size gets the size/length of the collection.
	Size() int

	// IsEmpty returns true if the collection is empty.
	IsEmpty() bool

	// NonEmpty returns true if the collection is non-empty.
	NonEmpty() bool

	// IsSequence returns true for lists, but false otherwise.
	IsSequence() bool

	// IsSet returns true for sets, but false otherwise.
	IsSet() bool

	// Head returns the first element of a list or an arbitrary element of a set or the contents of an option.
	// Panics if the collection is empty.
	Head() Num1

	// ToSlice returns a plain slice containing all the elements in the collection. This is useful for bespoke iteration etc.
	// For sequences, the order of the elements is simple and well defined.
	// For non-sequences (i.e. sets) the order of the elements is stable but not well defined. This means it will give
	// the same order each subsequent time it is used as it did the first time.
	ToSlice() []Num1

	// ToInts gets all the elements in a slice of the underlying type, []int.
	ToInts() []int

	// ToList gets all the elements in a List.
	ToList() Num1List

	// ToSet gets all the elements in a Set.
	ToSet() Num1Set

	// Send sends all elements along a channel of type Num1.
	// For sequences, the order of the elements is simple and well defined.
	// For non-sequences (i.e. sets) the order of the elements is stable but not well defined. This means it will give
	// the same order each subsequent time it is used as it did the first time.
	Send() <-chan Num1

	// Exists returns true if there exists at least one element in the collection that matches
	// the predicate supplied.
	Exists(predicate func(Num1) bool) bool

	// Forall returns true if every element in the collection matches the predicate supplied.
	Forall(predicate func(Num1) bool) bool

	// Foreach iterates over every element, executing a supplied function against each.
	Foreach(fn func(Num1))

	// Filter returns a new Num1Collection whose elements return true for a predicate function.
	// The relative order of the elements in the result is the same as in the
	// original collection.
	Filter(predicate func(Num1) bool) (result Num1Collection)

	// Partition returns two new Num1Collections whose elements return true or false for the predicate, p.
	// The first consists of all elements that satisfy the predicate and the second consists of
	// all elements that don't. The relative order of the elements in the results is the same as in the
	// original collection.
	Partition(p func(Num1) bool) (matching Num1Collection, others Num1Collection)

	// Equals verifies that another Num1Collection has the same size and elements as this one. Also,
	// if the collection is a sequence, the order must be the same.
	// Omitted if Num1 is not comparable.
	Equals(other Num1Collection) bool

	// Contains tests whether a given value is present in the collection.
	// Omitted if Num1 is not comparable.
	Contains(value Num1) bool

	// Sum sums Num1 elements.
	// Omitted if Num1 is not numeric.
	Sum() Num1

	// Mean computes the arithmetic mean of all elements. Panics if the collection is empty.
	// Omitted if Num1 is not numeric.
	Mean() float64

	// Min returns the minimum value of Num1List. In the case of multiple items being equally minimal,
	// the first such element is returned. Panics if the collection is empty.
	Min() Num1

	// Max returns the maximum value of Num1List. In the case of multiple items being equally maximal,
	// the first such element is returned. Panics if the collection is empty.
	Max() Num1

	// String gets a string representation of the collection. "[" and "]" surround
	// a comma-separated list of the elements.
	String() string

	// MkString gets a string representation of the collection. "[" and "]" surround a list
	// of the elements joined by the separator you provide.
	MkString(sep string) string

	// MkString3 gets a string representation of the collection. 'pfx' and 'sfx' surround a list
	// of the elements joined by the 'mid' separator you provide.
	MkString3(pfx, mid, sfx string) string
}

//-------------------------------------------------------------------------------------------------

// Num1List is a slice of type Num1. Use it where you would use []Num1.
// List values follow a similar pattern to Scala Lists and LinearSeqs in particular.
// Importantly, *none of its methods ever mutate a list*; they merely return new lists where required.
// When a list needs mutating, use normal Go slice operations, e.g. *append()*.
// For comparison with Scala, see e.g. http://www.scala-lang.org/api/2.11.7/#scala.collection.LinearSeq
type Num1List []Num1

//-------------------------------------------------------------------------------------------------

// NewNum1List constructs a new list containing the supplied values, if any.
func NewNum1List(values ...Num1) Num1List {
	list := make(Num1List, len(values))
	for i, v := range values {
		list[i] = v
	}
	return list
}

// NewNum1ListFromInts constructs a new Num1List from a []int.
func NewNum1ListFromInts(values []int) Num1List {
	list := make(Num1List, len(values))
	for i, v := range values {
		list[i] = Num1(v)
	}
	return list
}

// BuildNum1ListFromChan constructs a new Num1List from a channel that supplies a sequence
// of values until it is closed. The function doesn't return until then.
func BuildNum1ListFromChan(source <-chan Num1) Num1List {
	result := make(Num1List, 0)
	for v := range source {
		result = append(result, v)
	}
	return result
}

//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------

// Head gets the first element in the list. Head plus Tail include the whole list. Head is the opposite of Last.
// Panics if list is empty
func (list Num1List) Head() Num1 {
	return list[0]
}

// Last gets the last element in the list. Init plus Last include the whole list. Last is the opposite of Head.
// Panics if list is empty
func (list Num1List) Last() Num1 {
	return list[len(list)-1]
}

// Tail gets everything except the head. Head plus Tail include the whole list. Tail is the opposite of Init.
// Panics if list is empty
func (list Num1List) Tail() Num1Collection {
	return Num1List(list[1:])
}

// Init gets everything except the last. Init plus Last include the whole list. Init is the opposite of Tail.
// Panics if list is empty
func (list Num1List) Init() Num1Collection {
	return Num1List(list[:len(list)-1])
}

// IsEmpty tests whether Num1List is empty.
func (list Num1List) IsEmpty() bool {
	return len(list) == 0
}

// NonEmpty tests whether Num1List is empty.
func (list Num1List) NonEmpty() bool {
	return len(list) > 0
}

// IsSequence returns true for lists.
func (list Num1List) IsSequence() bool {
	return true
}

// IsSet returns false for lists.
func (list Num1List) IsSet() bool {
	return false
}

//-------------------------------------------------------------------------------------------------

// ToSlice gets all the list's elements in a plain slice. This is simply a type conversion and is hardly needed
// for lists, because the underlying type can be used directly also.
// It is part of the Num1Collection interface.
func (list Num1List) ToSlice() []Num1 {
	return []Num1(list)
}

// ToInts gets all the elements in a []int.
func (list Num1List) ToInts() []int {
	slice := make([]int, len(list))
	for i, v := range list {
		slice[i] = int(v)
	}
	return slice
}

// ToList simply returns the list in this case, but is part of the Collection interface.
func (list Num1List) ToList() Num1List {
	return list
}

// ToSet gets all the list's elements in a Num1Set.
func (list Num1List) ToSet() Num1Set {
	set := make(map[Num1]struct{})
	for _, v := range list {
		set[v] = struct{}{}
	}
	return Num1Set(set)
}

//-------------------------------------------------------------------------------------------------

// Size returns the number of items in the list - an alias of Len().
func (list Num1List) Size() int {
	return len(list)
}

// Len returns the number of items in the list - an alias of Size().
// This is one of the three methods in the standard sort.Interface.
func (list Num1List) Len() int {
	return len(list)
}

// Swap exchanges two elements, which is neceessary during sorting etc.
// This is one of the three methods in the standard sort.Interface.
func (list Num1List) Swap(i, j int) {
	list[i], list[j] = list[j], list[i]
}

// These methods require that Num1 be ordered.

// Less determines whether one specified element is less than another specified element.
// This is one of the three methods in the standard sort.Interface.
func (list Num1List) Less(i, j int) bool {
	return list[i] < list[j]
}

// Sort returns a new ordered Num1List.
func (list Num1List) Sort() Num1List {
	result := make(Num1List, len(list))
	copy(result, list)
	sort.Sort(result)
	return result
}

// IsSorted reports whether Num1List is sorted.
func (list Num1List) IsSorted() bool {
	return sort.IsSorted(list)
}

// SortDesc returns a new reverse-ordered Num1List.
func (list Num1List) SortDesc() Num1List {
	result := make(Num1List, len(list))
	copy(result, list)
	sort.Sort(sort.Reverse(result))
	return result
}

// IsSortedDesc reports whether Num1List is reverse-sorted.
func (list Num1List) IsSortedDesc() bool {
	return sort.IsSorted(sort.Reverse(list))
}

//-------------------------------------------------------------------------------------------------

// Exists verifies that one or more elements of Num1List return true for the passed func.
func (list Num1List) Exists(fn func(Num1) bool) bool {
	for _, v := range list {
		if fn(v) {
			return true
		}
	}
	return false
}

// Forall verifies that all elements of Num1List return true for the passed func.
func (list Num1List) Forall(fn func(Num1) bool) bool {
	for _, v := range list {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Foreach iterates over Num1List and executes the passed func against each element.
func (list Num1List) Foreach(fn func(Num1)) {
	for _, v := range list {
		fn(v)
	}
}

// Send gets a channel that will send all the elements in order.
func (list Num1List) Send() <-chan Num1 {
	ch := make(chan Num1)
	go func() {
		for _, v := range list {
			ch <- v
		}
		close(ch)
	}()
	return ch
}

// Reverse returns a copy of Num1List with all elements in the reverse order.
func (list Num1List) Reverse() Num1List {
	numItems := len(list)
	result := make(Num1List, numItems)
	last := numItems - 1
	for i, v := range list {
		result[last-i] = v
	}
	return result
}

// Shuffle returns a shuffled copy of Num1List, using a version of the Fisher-Yates shuffle.
func (list Num1List) Shuffle() Num1List {
	numItems := len(list)
	result := make(Num1List, numItems)
	copy(result, list)
	for i := 0; i < numItems; i++ {
		r := i + rand.Intn(numItems-i)
		result.Swap(i, r)
	}
	return result
}

//-------------------------------------------------------------------------------------------------

// Take returns a new Num1List containing the leading n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num1List) Take(n int) Num1List {
	if n > len(list) {
		return list
	} else {
		return list[0:n]
	}
}

// Drop returns a new Num1List without the leading n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num1List) Drop(n int) Num1List {
	l := len(list)
	if n > l {
		return list[l:]
	} else {
		return list[n:]
	}
}

// TakeLast returns a new Num1List containing the trailing n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num1List) TakeLast(n int) Num1List {
	l := len(list)
	if n > l {
		return list
	} else {
		return list[l-n:]
	}
}

// DropLast returns a new Num1List without the trailing n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num1List) DropLast(n int) Num1List {
	l := len(list)
	if n > l {
		return list[l:]
	} else {
		return list[0 : l-n]
	}
}

// TakeWhile returns a new Num1List containing the leading elements of the source list. Whilst the
// predicate p returns true, elements are added to the result. Once predicate p returns false, all remaining
// elemense are excluded.
func (list Num1List) TakeWhile(p func(Num1) bool) (result Num1List) {
	for _, v := range list {
		if p(v) {
			result = append(result, v)
		} else {
			return
		}
	}
	return
}

// DropWhile returns a new Num1List containing the trailing elements of the source list. Whilst the
// predicate p returns true, elements are excluded from the result. Once predicate p returns false, all remaining
// elemense are added.
func (list Num1List) DropWhile(p func(Num1) bool) (result Num1List) {
	adding := false
	for _, v := range list {
		if !p(v) || adding {
			adding = true
			result = append(result, v)
		}
	}
	return
}

//-------------------------------------------------------------------------------------------------

// Filter returns a new Num1List whose elements return true for func.
func (list Num1List) Filter(fn func(Num1) bool) Num1Collection {
	result := make(Num1List, 0, len(list)/2)
	for _, v := range list {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Partition returns two new Num1Lists whose elements return true or false for the predicate, p.
// The first result consists of all elements that satisfy the predicate and the second result consists of
// all elements that don't. The relative order of the elements in the results is the same as in the
// original list.
func (list Num1List) Partition(p func(Num1) bool) (Num1Collection, Num1Collection) {
	matching := make(Num1List, 0, len(list)/2)
	others := make(Num1List, 0, len(list)/2)
	for _, v := range list {
		if p(v) {
			matching = append(matching, v)
		} else {
			others = append(others, v)
		}
	}
	return matching, others
}

// CountBy gives the number elements of Num1List that return true for the passed predicate.
func (list Num1List) CountBy(predicate func(Num1) bool) (result int) {
	for _, v := range list {
		if predicate(v) {
			result++
		}
	}
	return
}

// MinBy returns an element of Num1List containing the minimum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such
// element is returned. Panics if there are no elements.
func (list Num1List) MinBy(less func(Num1, Num1) bool) (result Num1) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the minimum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// MaxBy returns an element of Num1List containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the first such
// element is returned. Panics if there are no elements.
func (list Num1List) MaxBy(less func(Num1, Num1) bool) (result Num1) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the maximum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(list[m], list[i]) {
			m = i
		}
	}
	result = list[m]
	return
}

// DistinctBy returns a new Num1List whose elements are unique, where equality is defined by a passed func.
func (list Num1List) DistinctBy(equal func(Num1, Num1) bool) (result Num1List) {
Outer:
	for _, v := range list {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

// IndexWhere finds the index of the first element satisfying some predicate. If none exists, -1 is returned.
func (list Num1List) IndexWhere(p func(Num1) bool) int {
	for i, v := range list {
		if p(v) {
			return i
		}
	}
	return -1
}

// IndexWhere2 finds the index of the first element satisfying some predicate at or after some start index.
// If none exists, -1 is returned.
func (list Num1List) IndexWhere2(p func(Num1) bool, from int) int {
	for i, v := range list {
		if i >= from && p(v) {
			return i
		}
	}
	return -1
}

// LastIndexWhere finds the index of the last element satisfying some predicate.
// If none exists, -1 is returned.
func (list Num1List) LastIndexWhere(p func(Num1) bool) int {
	for i := len(list) - 1; i >= 0; i-- {
		v := list[i]
		if p(v) {
			return i
		}
	}
	return -1
}

// LastIndexWhere2 finds the index of the last element satisfying some predicate at or after some start index.
// If none exists, -1 is returned.
func (list Num1List) LastIndexWhere2(p func(Num1) bool, before int) int {
	for i := len(list) - 1; i >= 0; i-- {
		v := list[i]
		if i <= before && p(v) {
			return i
		}
	}
	return -1
}

// Equals verifies that another Num1Collection has the same size and elements as this one. Also,
// because this collection is a sequence, the order must be the same.
// Omitted if Num1 is not comparable.
func (list Num1List) Equals(other Num1Collection) bool {
	if len(list) != other.Size() {
		return false
	}
	eq := true
	i := 0
	other.Foreach(func(a Num1) {
		if eq {
			v := list[i]
			if v != a {
				eq = false
			}
			i++
		}
	})
	return eq
}

//-------------------------------------------------------------------------------------------------
// These methods are provided because Num1 is comparable.

// IndexOf finds the index of the first element specified. If none exists, -1 is returned.
func (list Num1List) IndexOf(value Num1) int {
	for i, v := range list {
		if v == value {
			return i
		}
	}
	return -1
}

// IndexOf2 finds the index of the first element specified at or after some start index.
// If none exists, -1 is returned.
func (list Num1List) IndexOf2(value Num1, from int) int {
	for i, v := range list {
		if i >= from && v == value {
			return i
		}
	}
	return -1
}

// Contains verifies that a given value is contained in Num1List.
func (list Num1List) Contains(value Num1) bool {
	for _, v := range list {
		if v == value {
			return true
		}
	}
	return false
}

// Count gives the number elements of Num1List that match a certain value.
func (list Num1List) Count(value Num1) (result int) {
	for _, v := range list {
		if v == value {
			result++
		}
	}
	return
}

// Distinct returns a new Num1List whose elements are unique, retaining the original order.
func (list Num1List) Distinct() Num1Collection {
	result := make(Num1List, 0)
	appended := make(map[Num1]bool)
	for _, v := range list {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

//-------------------------------------------------------------------------------------------------
// These methods are provided because Num1 is numeric.

// Sum sums all elements in the list.
func (list Num1List) Sum() (result Num1) {
	for _, v := range list {
		result += v
	}
	return
}

// Mean computes the arithmetic mean of all elements.
// Panics if the list is empty.
func (list Num1List) Mean() float64 {
	l := len(list)
	if l == 0 {
		panic("Cannot compute the arithmetic mean of zero-length Num1List")
	}
	sum := list.Sum()
	return float64(sum) / float64(l)
}

//-------------------------------------------------------------------------------------------------
// These methods are provided because Num1 is ordered.

// Min returns the element with the minimum value. In the case of multiple items being equally minimal,
// the first such element is returned. Panics if the collection is empty.
func (list Num1List) Min() (result Num1) {
	if len(list) == 0 {
		panic("Cannot determine the Min of an empty list.")
	}
	result = list[0]
	for _, v := range list {
		if v < result {
			result = v
		}
	}
	return
}

// Max returns the element with the maximum value. In the case of multiple items being equally maximal,
// the first such element is returned. Panics if the collection is empty.
func (list Num1List) Max() (result Num1) {
	if len(list) == 0 {
		panic("Cannot determine the Max of an empty list.")
	}
	result = list[0]
	for _, v := range list {
		if v > result {
			result = v
		}
	}
	return
}

//-------------------------------------------------------------------------------------------------

// String implements the Stringer interface to render the list as a comma-separated string enclosed in square brackets.
func (list Num1List) String() string {
	return list.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string using a supplied separator. No enclosing marks are added.
func (list Num1List) MkString(sep string) string {
	return list.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string, using the prefix, separator and suffix supplied.
func (list Num1List) MkString3(pfx, mid, sfx string) string {
	b := bytes.Buffer{}
	b.WriteString(pfx)
	l := len(list)
	if l > 0 {
		v := list[0]
		b.WriteString(fmt.Sprintf("%v", v))
		for i := 1; i < l; i++ {
			v := list[i]
			b.WriteString(mid)
			b.WriteString(fmt.Sprintf("%v", v))
		}
	}
	b.WriteString(sfx)
	return b.String()
}

//-------------------------------------------------------------------------------------------------
// Methods to interface lists with options.

// First returns the first element that returns true for the passed func. Returns none if no elements return true.
func (list Num1List) Find(fn func(Num1) bool) OptionalNum1 {
	for _, v := range list {
		if fn(v) {
			//return SomeNum1(v)
		}
	}
	return NoNum1()
}

// HeadOption gets the first item in the list, provided there is one.
func (list Num1List) HeadOption() OptionalNum1 {
	l := len(list)
	if l > 0 {
		return SomeNum1(list[0])
	} else {
		return NoNum1()
	}
}

// TailOption gets the last item in the list, provided there is one.
func (list Num1List) LastOption() OptionalNum1 {
	l := len(list)
	if l > 0 {
		return SomeNum1(list[l-1])
	} else {
		return NoNum1()
	}
}

//-------------------------------------------------------------------------------------------------
// List:MapTo[Foo]

// MapToFoo transforms Num1List to FooList.
func (list Num1List) MapToFoo(fn func(Num1) Foo) FooCollection {
	result := make(FooList, 0, len(list))
	for _, v := range list {
		u := fn(v)
		result = append(result, u)
	}
	return result
}

// FlatMapToFoo transforms Num1List to FooList, by repeatedly
// calling the supplied function and concatenating the results as a single flat list.
func (list Num1List) FlatMapToFoo(fn func(Num1) FooCollection) FooCollection {
	result := make(FooList, 0, len(list))
	for _, v := range list {
		u := fn(v)
		if u.NonEmpty() {
			result = append(result, (u.ToList())...)
		}
	}
	return result
}

//-------------------------------------------------------------------------------------------------

// OptionalNum1 is an optional of type Num1. Use it where you want to be explicit about
// the presence or absence of data.
//
// Optional values follow a similar pattern to Scala Options. In particular, an option is a collection
// with a maximum cardinality of one. As such, options can be converted to/from lists and sets.
// See e.g. http://www.scala-lang.org/api/2.11.7/index.html#scala.Option
type OptionalNum1 struct {
	x *Num1
}

// shared none value
var noneNum1 = OptionalNum1{nil}

// NoNum1 gets an empty instance.
func NoNum1() OptionalNum1 {
	return noneNum1
}

// SomeNum1 gets a non-empty instance wrapping some value *x*.
func SomeNum1(x Num1) OptionalNum1 {

	return OptionalNum1{&x}

}

//-------------------------------------------------------------------------------------------------

// panics if option is empty
func (o OptionalNum1) Head() Num1 {
	return o.Get()
}

func (o OptionalNum1) Get() Num1 {
	if o.IsEmpty() {
		panic("Attempt to access non-existent value")
	}
	return *o.x
}

func (o OptionalNum1) GetOrElse(d func() Num1) Num1 {
	if o.IsEmpty() {
		return d()
	}
	return *o.x
}

func (o OptionalNum1) OrElse(alternative func() OptionalNum1) OptionalNum1 {
	if o.IsEmpty() {
		return alternative()
	}
	return o
}

//-------------------------------------------------------------------------------------------------

func (o OptionalNum1) Size() int {
	if o.IsEmpty() {
		return 0
	}
	return 1
}

func (o OptionalNum1) Len() int {
	return o.Size()
}

func (o OptionalNum1) IsEmpty() bool {
	return o.x == nil
}

func (o OptionalNum1) NonEmpty() bool {
	return o.x != nil
}

// IsSequence returns false for options.
func (o OptionalNum1) IsSequence() bool {
	return false
}

// IsSet returns false for options.
func (o OptionalNum1) IsSet() bool {
	return false
}

// IsDefined returns true if the option is defined, i.e. non-empty. This is an alias for NonEmpty().
func (o OptionalNum1) IsDefined() bool {
	return o.NonEmpty()
}

//-------------------------------------------------------------------------------------------------

func (o OptionalNum1) Find(predicate func(Num1) bool) OptionalNum1 {
	if o.IsEmpty() {
		return o
	}
	if predicate(*o.x) {
		return o
	}
	return noneNum1
}

func (o OptionalNum1) Exists(predicate func(Num1) bool) bool {
	if o.IsEmpty() {
		return false
	}
	return predicate(*o.x)
}

func (o OptionalNum1) Forall(predicate func(Num1) bool) bool {
	if o.IsEmpty() {
		return true
	}
	return predicate(*o.x)
}

func (o OptionalNum1) Foreach(fn func(Num1)) {
	if o.NonEmpty() {
		fn(*o.x)
	}
}

// Send gets a channel that will send all the elements in order.
func (o OptionalNum1) Send() <-chan Num1 {
	ch := make(chan Num1)
	go func() {
		if o.NonEmpty() {
			ch <- *o.x
		}
		close(ch)
	}()
	return ch
}

func (o OptionalNum1) Filter(predicate func(Num1) bool) Num1Collection {
	return o.Find(predicate)
}

func (o OptionalNum1) Partition(predicate func(Num1) bool) (Num1Collection, Num1Collection) {
	if o.IsEmpty() {
		return o, o
	}
	if predicate(*o.x) {
		return o, noneNum1
	}
	return noneNum1, o
}

func (o OptionalNum1) ToSlice() []Num1 {
	slice := make([]Num1, o.Size())
	if o.NonEmpty() {
		slice[0] = *o.x
	}
	return slice
}

// ToInts gets all the elements in a []int.
func (o OptionalNum1) ToInts() []int {
	slice := make([]int, o.Size())
	if o.NonEmpty() {
		slice[0] = int(*o.x)
	}
	return slice
}

// ToList gets the option's element in a Num1List.
func (o OptionalNum1) ToList() Num1List {
	return Num1List(o.ToSlice())
}

// ToSet gets the option's element in a Num1Set.
func (o OptionalNum1) ToSet() Num1Set {
	return NewNum1Set(o.ToSlice()...)
}

//-------------------------------------------------------------------------------------------------
// These methods require Num1 be comparable.

// Equals verifies that one or more elements of Num1List return true for the passed func.
func (o OptionalNum1) Equals(other Num1Collection) bool {
	if o.IsEmpty() {
		return other.IsEmpty()
	}
	if other.IsEmpty() || other.Size() > 1 {
		return false
	}
	a := o.x
	s := other.ToSlice()
	b := s[0]
	return *a == b
}

func (o OptionalNum1) Contains(value Num1) bool {
	if o.IsEmpty() {
		return false
	}
	return *(o.x) == value
}

func (o OptionalNum1) Count(value Num1) int {
	if o.Contains(value) {
		return 1
	}
	return 0
}

// Distinct returns a new Num1Collection whose elements are all unique. For options, this simply returns the
// receiver.
// Omitted if Num1 is not comparable.
func (o OptionalNum1) Distinct() Num1Collection {
	return o
}

// Min returns the minimum value of Num1List. In the case of multiple items being equally minimal,
// the first such element is returned. Panics if the collection is empty.
func (o OptionalNum1) Min() Num1 {
	return o.Get()
}

// Max returns the maximum value of Num1List. In the case of multiple items being equally maximal,
// the first such element is returned. Panics if the collection is empty.
func (o OptionalNum1) Max() Num1 {
	return o.Get()
}

//-------------------------------------------------------------------------------------------------

// Sum sums Num1 elements.
// Omitted if Num1 is not numeric.
func (o OptionalNum1) Sum() Num1 {

	if o.IsEmpty() {
		return 0
	}
	return *(o.x)

}

// Mean computes the arithmetic mean of all elements.
// Panics if the list is empty.
func (o OptionalNum1) Mean() float64 {
	if o.IsEmpty() {
		panic("Cannot compute the arithmetic mean of zero-length OptionalNum1")
	}
	return float64(*(o.x))
}

//-------------------------------------------------------------------------------------------------

// String implements the Stringer interface to render the option as an array of one element.
func (o OptionalNum1) String() string {
	return o.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string.
func (o OptionalNum1) MkString(sep string) string {
	return o.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string.
func (o OptionalNum1) MkString3(pfx, mid, sfx string) string {
	if o.IsEmpty() {
		return fmt.Sprintf("%s%s", pfx, sfx)
	}
	return fmt.Sprintf("%s%v%s", pfx, *(o.x), sfx)
}

//-------------------------------------------------------------------------------------------------

// Num1Set is a typesafe set of Num1 items.
// The implementation is based on an underyling Go map, which can be manipulated directly,
// but otherwise instances are essentially immutable.
// The set-agebra functions *Union*, *Intersection* and *Difference* allow new variants to be constructed
// easily; these methods do not modify the input sets.
type Num1Set map[Num1]struct{}

//-------------------------------------------------------------------------------------------------

// NewNum1Set constructs a new set containing the supplied values, if any.
func NewNum1Set(values ...Num1) Num1Set {
	set := make(map[Num1]struct{})
	for _, v := range values {
		set[v] = struct{}{}
	}
	return Num1Set(set)
}

// BuildNum1SetFrom constructs a new Num1Set from a channel that supplies a stream of values
// until it is closed. The function returns all these values in a set (i.e. without any duplicates).
func BuildNum1SetFrom(source <-chan Num1) Num1Set {
	set := make(map[Num1]struct{})
	for v := range source {
		set[v] = struct{}{}
	}
	return Num1Set(set)
}

//-------------------------------------------------------------------------------------------------

// IsSequence returns false for sets.
func (set Num1Set) IsSequence() bool {
	return false
}

// IsSet returns true for sets.
func (set Num1Set) IsSet() bool {
	return true
}

func (set Num1Set) Size() int {
	return len(set)
}

func (set Num1Set) IsEmpty() bool {
	return len(set) == 0
}

func (set Num1Set) NonEmpty() bool {
	return len(set) > 0
}

// Head gets an arbitrary element.
func (set Num1Set) Head() Num1 {
	for v := range set {
		return v
	}
	panic("Set is empty")
}

// ToSlice gets all the set's elements in a plain slice.
func (set Num1Set) ToSlice() []Num1 {
	slice := make([]Num1, set.Size())
	i := 0
	for v := range set {
		slice[i] = v
		i++
	}
	return slice
}

// ToInts gets all the elements in a []int.
func (set Num1Set) ToInts() []int {
	slice := make([]int, len(set))
	i := 0
	for v := range set {
		slice[i] = int(v)
		i++
	}
	return slice
}

// ToList gets all the set's elements in a in SetList.
func (set Num1Set) ToList() Num1List {
	return Num1List(set.ToSlice())
}

// ToSet gets the current set, which requires no further conversion.
func (set Num1Set) ToSet() Num1Set {
	return set
}

// Contains tests whether an item is already in the Num1Set.
func (set Num1Set) Contains(i Num1) bool {
	_, found := set[i]
	return found
}

// ContainsAll tests whether many items are all in the Num1Set.
func (set Num1Set) ContainsAll(i ...Num1) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

func (set Num1Set) actualSubset(other Num1Set) bool {
	for item := range set {
		if !other.Contains(item) {
			return false
		}
	}
	return true
}

// Equals determines if two sets are equal to each other.
// They are considered equal if both are the same size and both have the same items.
func (set Num1Set) Equals(other Num1Collection) bool {
	otherSet, isSet := other.(Num1Set)
	return isSet && set.Size() == other.Size() && set.actualSubset(otherSet)
}

// IsSubset determines if every item in the other set is in this set.
func (set Num1Set) IsSubset(other Num1Set) bool {
	return set.Size() <= other.Size() && set.actualSubset(other)
}

// IsProperSubset determines if every item in the other set is in this set and this set is
// smaller than the other.
func (set Num1Set) IsProperSubset(other Num1Set) bool {
	return set.Size() < other.Size() && set.actualSubset(other)
}

// IsSuperset determines if every item of this set is in the other set.
func (set Num1Set) IsSuperset(other Num1Set) bool {
	return other.IsSubset(set)
}

// Union returns a new set with all items in both sets.
func (set Num1Set) Union(other Num1Set) Num1Set {
	union := NewNum1Set()
	for item := range set {
		union[item] = struct{}{}
	}
	for item := range other {
		union[item] = struct{}{}
	}
	return union
}

// Intersection returns a new set with items that exist only in both sets.
func (set Num1Set) Intersection(other Num1Set) Num1Set {
	intersection := NewNum1Set()
	// loop over the smaller set
	if set.Size() < other.Size() {
		for item := range set {
			if other.Contains(item) {
				intersection[item] = struct{}{}
			}
		}
	} else {
		for item := range other {
			if set.Contains(item) {
				intersection[item] = struct{}{}
			}
		}
	}
	return intersection
}

// Difference returns a new set with items in the current set but not in the other set
func (set Num1Set) Difference(other Num1Set) Num1Set {
	diffs := NewNum1Set()
	for item := range set {
		if !other.Contains(item) {
			diffs[item] = struct{}{}
		}
	}
	return diffs
}

// Add creates a new set with elements added. This is similar to Union, but takes a slice of extra values.
// The receiver is not modified.
func (set Num1Set) Add(others ...Num1) Num1Set {
	added := NewNum1Set()
	for item := range set {
		added[item] = struct{}{}
	}
	for _, item := range others {
		added[item] = struct{}{}
	}
	return added
}

// Remove creates a new set with elements removed. This is similar to Difference, but takes a slice of unwanted values.
// The receiver is not modified.
func (set Num1Set) Remove(unwanted ...Num1) Num1Set {
	removed := NewNum1Set()
	for item := range set {
		removed[item] = struct{}{}
	}
	for _, item := range unwanted {
		delete(removed, item)
	}
	return removed
}

// Exists verifies that one or more elements of Num1Set return true for the passed func.
func (set Num1Set) Exists(fn func(Num1) bool) bool {
	for v := range set {
		if fn(v) {
			return true
		}
	}
	return false
}

// Forall verifies that all elements of Num1Set return true for the passed func.
func (set Num1Set) Forall(fn func(Num1) bool) bool {
	for v := range set {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Foreach iterates over Num1Set and executes the passed func against each element.
// The order of the elements is not well defined but is probably repeatably stable until the set is changed.
func (set Num1Set) Foreach(fn func(Num1)) {
	for v := range set {
		fn(v)
	}
}

// Send sends all elements along a channel of type Num1.
// The order of the elements is not well defined but is probably repeatably stable until the set is changed.
func (set Num1Set) Send() <-chan Num1 {
	ch := make(chan Num1)
	go func() {
		for v := range set {
			ch <- v
		}
		close(ch)
	}()
	return ch
}

// Filter returns a new Num1Set whose elements return true for func.
func (set Num1Set) Filter(fn func(Num1) bool) Num1Collection {
	result := make(map[Num1]struct{})
	for v := range set {
		if fn(v) {
			result[v] = struct{}{}
		}
	}
	return Num1Set(result)
}

// Partition returns two new Num1Lists whose elements return true or false for the predicate, p.
// The first result consists of all elements that satisfy the predicate and the second result consists of
// all elements that don't. The relative order of the elements in the results is the same as in the
// original set.
func (set Num1Set) Partition(p func(Num1) bool) (Num1Collection, Num1Collection) {
	matching := make(map[Num1]struct{})
	others := make(map[Num1]struct{})
	for v := range set {
		if p(v) {
			matching[v] = struct{}{}
		} else {
			others[v] = struct{}{}
		}
	}
	return Num1Set(matching), Num1Set(others)
}

// CountBy gives the number elements of Num1Set that return true for the passed predicate.
func (set Num1Set) CountBy(predicate func(Num1) bool) (result int) {
	for v := range set {
		if predicate(v) {
			result++
		}
	}
	return
}

// MinBy returns an element of Num1Set containing the minimum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such
// element is returned. Panics if there are no elements.
func (set Num1Set) MinBy(less func(Num1, Num1) bool) (result Num1) {
	l := len(set)
	if l == 0 {
		panic("Cannot determine the minimum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if less(v, result) {
			result = v
		}
	}
	return
}

// MaxBy returns an element of Num1Set containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such
// element is returned. Panics if there are no elements.
func (set Num1Set) MaxBy(less func(Num1, Num1) bool) (result Num1) {
	l := len(set)
	if l == 0 {
		panic("Cannot determine the maximum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if less(result, v) {
			result = v
		}
	}
	return
}

// These methods require Num1 be numeric.

// Sum sums all elements in the set.
func (set Num1Set) Sum() (result Num1) {
	for v := range set {
		result += v
	}
	return
}

// Mean computes the arithmetic mean of all elements.
// Panics if the set is empty.
func (set Num1Set) Mean() float64 {
	l := len(set)
	if l == 0 {
		panic("Cannot compute the arithmetic mean of zero-length Num1Set")
	}
	sum := set.Sum()
	return float64(sum) / float64(l)
}

//-------------------------------------------------------------------------------------------------
// These methods require Num1 be ordered.

// Min returns the element with the minimum value. In the case of multiple items being equally minimal,
// any such element is returned. Panics if the collection is empty.
func (set Num1Set) Min() (result Num1) {
	if len(set) == 0 {
		panic("Cannot determine the minimum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if v < result {
			result = v
		}
	}
	return
}

// Max returns the element with the maximum value. In the case of multiple items being equally maximal,
// any such element is returned. Panics if the collection is empty.
func (set Num1Set) Max() (result Num1) {
	if len(set) == 0 {
		panic("Cannot determine the maximum of an empty set.")
	}
	first := true
	for v := range set {
		if first {
			first = false
			result = v
		} else if v > result {
			result = v
		}
	}
	return
}

// String implements the Stringer interface to render the set as a comma-separated array.
func (set Num1Set) String() string {
	return set.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string.
func (set Num1Set) MkString(sep string) string {
	return set.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string.
func (set Num1Set) MkString3(pfx, mid, sfx string) string {
	b := bytes.Buffer{}
	b.WriteString(pfx)
	l := len(set)
	if l > 0 {
		sep := ""
		for v := range set {
			b.WriteString(sep)
			b.WriteString(fmt.Sprintf("%v", v))
			sep = mid
		}
	}
	b.WriteString(sfx)
	return b.String()
}

//-------------------------------------------------------------------------------------------------

// This plumbing suite provides standard functions for piping data between goroutines.
// All these functions run until the input channel is closed (or all input channels are closed, if
// multiple). They then close their output channel(s).
// None of these functions create a goroutine - this must be done at the call site.

//-------------------------------------------------------------------------------------------------

// Num1Generator produces a stream of Num1 based on a supplied generator function.
// The function fn is invoked N times with the integers from 0 to N-1. Each result is sent out.
// Finally, the output channel is closed and the generator terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Generator(out chan<- Num1, iterations int, fn func(int) Num1) {
	Num1Generator3(out, 0, iterations-1, 1, fn)
}

// Num1Generator produces a stream of Num1 based on a supplied generator function.
// The function fn is invoked *(|to - from|) / |stride|* times with the integers in the range specified by
// from, to and stride. If stride is negative, from should be greater than to.
// For each iteration, the computed function result is sent out.
// If stride is zero, the loop never terminates. Otherwise, after the generator has reached the
// loop end, the output channel is closed and the generator terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Generator3(out chan<- Num1, from, to, stride int, fn func(int) Num1) {
	if (from > to && stride > 0) || (from < to && stride < 0) {
		panic("Loop conditions are divergent.")
	}
	if from > to && stride < 0 {
		for i := from; i >= to; i += stride {
			out <- fn(i)
		}
	} else {
		for i := from; i <= to; i += stride {
			out <- fn(i)
		}
	}
	close(out)
}

// Num1Delta duplicates a stream of Num1 to two output channels.
// When the sender closes the input channel, both output channels are closed then the function terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Delta(in <-chan Num1, out1, out2 chan<- Num1) {
	for v := range in {
		select {
		case out1 <- v:
			out2 <- v
		case out2 <- v:
			out1 <- v
		}
	}
	close(out1)
	close(out2)
}

// Num1Zip2 interleaves two streams of Num1.
// Each input channel is used in turn, alternating between them.
// The function terminates when *both* input channels have been closed by their senders.
// The output channel is then closed also.
//
// It is part of the Plumbing function suite for Num1.
func Num1Zip2(in1, in2 <-chan Num1, out chan<- Num1) {
	closed2 := false
	for v := range in1 {
		out <- v
		v, ok := <-in2
		if ok {
			out <- v
		} else {
			closed2 = true
		}
	}
	// need to drain in2 as well?
	if !closed2 {
		for _ = range in2 {
		}
	}
	close(out)
}

// Num1Mux2 multiplexes two streams of Num1 into a single output channel.
// Each input channel is used as soon as it is ready.
// When a signal is received from the closer channel, the output channel is then closed.
// Concurrently, both input channels are then passed into blackholes that comsume them until they too are closed,
// and the function terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Mux2(in1, in2 <-chan Num1, closer <-chan bool, out chan<- Num1) {
	running := true
	for running {
		select {
		case v := <-in1:
			out <- v
		case v := <-in2:
			out <- v
		case _ = <-closer:
			running = false
		}
	}
	go Num1BlackHole(in1)
	go Num1BlackHole(in2)
	close(out)
}

// Num1BlackHole silently consumes a stream of Num1.
// It terminates when the sender closes the channel.
//
// It is part of the Plumbing function suite for Num1.
func Num1BlackHole(in <-chan Num1) {
	for _ = range in {
		// om nom nom
	}
}

// Num1Filter filters a stream of Num1, silently dropping elements that do not match the predicate p.
// When the sender closes the input channel, the output channel is closed then the function terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Filter(in <-chan Num1, out chan<- Num1, p func(Num1) bool) {
	for v := range in {
		if p(v) {
			out <- v
		}
	}
	close(out)
}

// Num1Partition filters a stream of Num1 into two output streams using a predicate p, those that
// match and all others.
// When the sender closes the input channel, both output channels are closed then the function terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Partition(in <-chan Num1, matching, others chan<- Num1, p func(Num1) bool) {
	for v := range in {
		if p(v) {
			matching <- v
		} else {
			others <- v
		}
	}
	close(matching)
	close(others)
}

// Num1Map transforms a stream of Num1 by applying a function fn to each item in the stream.
// When the sender closes the input channel, the output channel is closed then the function terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1Map(in <-chan Num1, out chan<- Num1, fn func(Num1) Num1) {
	for v := range in {
		out <- fn(v)
	}
	close(out)
}

// Num1FlatMap transforms a stream of Num1 by applying a function fn to each item in the stream that
// gives zero or more results, all of which are sent out.
// When the sender closes the input channel, the output channel is closed then the function terminates.
//
// It is part of the Plumbing function suite for Num1.
func Num1FlatMap(in <-chan Num1, out chan<- Num1, fn func(Num1) Num1Collection) {
	for vi := range in {
		c := fn(vi)
		if c.NonEmpty() {
			for vo := range c.Send() {
				out <- vo
			}
		}
	}
	close(out)
}

// List flags: {Collection:false List:true Option:true Set:true Plumbing:false Tag:map[MapTo:true Plumbing:true]}
