// Generated by: setup
// TypeWriter: Option
// Directive: +test on WotHasMap

package main

import "fmt"

//-------------------------------------------------------------------------------------------------

// WotHasMapCollection is an interface for collections of type WotHasMap, including sets, lists and options (where present).
type WotHasMapCollection interface {
	// Size gets the size/length of the collection.
	Size() int

	// IsEmpty returns true if the collection is empty.
	IsEmpty() bool

	// NonEmpty returns true if the collection is non-empty.
	NonEmpty() bool

	// IsSequence returns true for lists, but false otherwise.
	IsSequence() bool

	// IsSet returns true for sets, but false otherwise.
	IsSet() bool

	// Head returns the first element of a list or an arbitrary element of a set or the contents of an option.
	// Panics if the collection is empty.
	Head() WotHasMap

	// ToSlice returns a plain slice containing all the elements in the collection. This is useful for bespoke iteration etc.
	// For sequences, the order of the elements is simple and well defined.
	// For non-sequences (i.e. sets) the order of the elements is stable but not well defined. This means it will give
	// the same order each subsequent time it is used as it did the first time.
	ToSlice() []WotHasMap

	// Send sends all elements along a channel of type WotHasMap.
	// For sequences, the order of the elements is simple and well defined.
	// For non-sequences (i.e. sets) the order of the elements is stable but not well defined. This means it will give
	// the same order each subsequent time it is used as it did the first time.
	Send() <-chan WotHasMap

	// Exists returns true if there exists at least one element in the collection that matches
	// the predicate supplied.
	Exists(predicate func(WotHasMap) bool) bool

	// Forall returns true if every element in the collection matches the predicate supplied.
	Forall(predicate func(WotHasMap) bool) bool

	// Foreach iterates over every element, executing a supplied function against each.
	Foreach(fn func(WotHasMap))

	// Filter returns a new WotHasMapCollection whose elements return true for a predicate function.
	// The relative order of the elements in the result is the same as in the
	// original collection.
	Filter(predicate func(WotHasMap) bool) (result WotHasMapCollection)

	// Partition returns two new WotHasMapCollections whose elements return true or false for the predicate, p.
	// The first consists of all elements that satisfy the predicate and the second consists of
	// all elements that don't. The relative order of the elements in the results is the same as in the
	// original collection.
	Partition(p func(WotHasMap) bool) (matching WotHasMapCollection, others WotHasMapCollection)

	// Min returns an element of WotHasMapList containing the minimum value, when compared to other elements
	// using a specified comparator function defining ‘less’. For ordered sequences, Min returns the first such element.
	// Panics if the collection is empty.
	Min(less func(WotHasMap, WotHasMap) bool) WotHasMap

	// Max returns an element of WotHasMapList containing the maximum value, when compared to other elements
	// using a specified comparator function defining ‘less’. For ordered sequences, Max returns the first such element.
	// Panics if the collection is empty.
	Max(less func(WotHasMap, WotHasMap) bool) WotHasMap

	// String gets a string representation of the collection. "[" and "]" surround
	// a comma-separated list of the elements.
	String() string

	// MkString gets a string representation of the collection. "[" and "]" surround a list
	// of the elements joined by the separator you provide.
	MkString(sep string) string

	// MkString3 gets a string representation of the collection. 'pfx' and 'sfx' surround a list
	// of the elements joined by the 'mid' separator you provide.
	MkString3(pfx, mid, sfx string) string
}

//-------------------------------------------------------------------------------------------------

// OptionalWotHasMap is an optional of type WotHasMap. Use it where you want to be explicit about
// the presence or absence of data.
//
// Optional values follow a similar pattern to Scala Options. In particular, an option is a collection
// with a maximum cardinality of one. As such, options can be converted to/from lists and sets.
// See e.g. http://www.scala-lang.org/api/2.11.7/index.html#scala.Option
type OptionalWotHasMap struct {
	x *WotHasMap
}

// shared none value
var noneWotHasMap = OptionalWotHasMap{nil}

// NoWotHasMap gets an empty instance.
func NoWotHasMap() OptionalWotHasMap {
	return noneWotHasMap
}

// SomeWotHasMap gets a non-empty instance wrapping some value *x*.
func SomeWotHasMap(x WotHasMap) OptionalWotHasMap {

	return OptionalWotHasMap{&x}

}

//-------------------------------------------------------------------------------------------------

// panics if option is empty
func (o OptionalWotHasMap) Head() WotHasMap {
	return o.Get()
}

func (o OptionalWotHasMap) Get() WotHasMap {
	if o.IsEmpty() {
		panic("Attempt to access non-existent value")
	}
	return *o.x
}

func (o OptionalWotHasMap) GetOrElse(d func() WotHasMap) WotHasMap {
	if o.IsEmpty() {
		return d()
	}
	return *o.x
}

func (o OptionalWotHasMap) OrElse(alternative func() OptionalWotHasMap) OptionalWotHasMap {
	if o.IsEmpty() {
		return alternative()
	}
	return o
}

//-------------------------------------------------------------------------------------------------

func (o OptionalWotHasMap) Size() int {
	if o.IsEmpty() {
		return 0
	}
	return 1
}

func (o OptionalWotHasMap) Len() int {
	return o.Size()
}

func (o OptionalWotHasMap) IsEmpty() bool {
	return o.x == nil
}

func (o OptionalWotHasMap) NonEmpty() bool {
	return o.x != nil
}

// IsSequence returns false for options.
func (o OptionalWotHasMap) IsSequence() bool {
	return false
}

// IsSet returns false for options.
func (o OptionalWotHasMap) IsSet() bool {
	return false
}

// IsDefined returns true if the option is defined, i.e. non-empty. This is an alias for NonEmpty().
func (o OptionalWotHasMap) IsDefined() bool {
	return o.NonEmpty()
}

//-------------------------------------------------------------------------------------------------

func (o OptionalWotHasMap) Find(predicate func(WotHasMap) bool) OptionalWotHasMap {
	if o.IsEmpty() {
		return o
	}
	if predicate(*o.x) {
		return o
	}
	return noneWotHasMap
}

func (o OptionalWotHasMap) Exists(predicate func(WotHasMap) bool) bool {
	if o.IsEmpty() {
		return false
	}
	return predicate(*o.x)
}

func (o OptionalWotHasMap) Forall(predicate func(WotHasMap) bool) bool {
	if o.IsEmpty() {
		return true
	}
	return predicate(*o.x)
}

func (o OptionalWotHasMap) Foreach(fn func(WotHasMap)) {
	if o.NonEmpty() {
		fn(*o.x)
	}
}

// Send gets a channel that will send all the elements in order.
func (o OptionalWotHasMap) Send() <-chan WotHasMap {
	ch := make(chan WotHasMap)
	go func() {
		if o.NonEmpty() {
			ch <- *o.x
		}
		close(ch)
	}()
	return ch
}

func (o OptionalWotHasMap) Filter(predicate func(WotHasMap) bool) WotHasMapCollection {
	return o.Find(predicate)
}

func (o OptionalWotHasMap) Partition(predicate func(WotHasMap) bool) (WotHasMapCollection, WotHasMapCollection) {
	if o.IsEmpty() {
		return o, o
	}
	if predicate(*o.x) {
		return o, noneWotHasMap
	}
	return noneWotHasMap, o
}

func (o OptionalWotHasMap) ToSlice() []WotHasMap {
	slice := make([]WotHasMap, o.Size())
	if o.NonEmpty() {
		slice[0] = *o.x
	}
	return slice
}

// Min returns an element of WotHasMapList containing the minimum value, when compared to other elements
// using a specified comparator function defining ‘less’. For ordered sequences, Min returns the first such element.
// Panics if the collection is empty.
func (o OptionalWotHasMap) Min(less func(WotHasMap, WotHasMap) bool) WotHasMap {
	return o.Get()
}

// Max returns an element of WotHasMapList containing the maximum value, when compared to other elements
// using a specified comparator function defining ‘less’. For ordered sequences, Max returns the first such element.
// Panics if the collection is empty.
func (o OptionalWotHasMap) Max(less func(WotHasMap, WotHasMap) bool) WotHasMap {
	return o.Get()
}

//-------------------------------------------------------------------------------------------------

// String implements the Stringer interface to render the option as an array of one element.
func (o OptionalWotHasMap) String() string {
	return o.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string.
func (o OptionalWotHasMap) MkString(sep string) string {
	return o.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string.
func (o OptionalWotHasMap) MkString3(pfx, mid, sfx string) string {
	if o.IsEmpty() {
		return fmt.Sprintf("%s%s", pfx, sfx)
	}
	return fmt.Sprintf("%s%v%s", pfx, *(o.x), sfx)
}

// Option flags: {Collection:false List:false Option:true Set:false Plumbing:false Tag:map[]}
