// Generated by: setup
// TypeWriter: List
// Directive: +test on *Num2

package main

import (
	"bytes"
	"fmt"
	"math/rand"
)

//-------------------------------------------------------------------------------------------------
// Num2Collection is an interface for collections of type Num2, including sets, lists and options (where present).
type Num2Collection interface {
	// Size gets the size/length of the collection.
	Size() int

	// IsEmpty returns true if the collection is empty.
	IsEmpty() bool

	// NonEmpty returns true if the collection is non-empty.
	NonEmpty() bool

	// IsSequence returns true for lists, but false otherwise.
	IsSequence() bool

	// IsSet returns true for sets, but false otherwise.
	IsSet() bool

	// Head returns the first element of a list or an arbitrary element of a set or the contents of an option.
	// Panics if the collection is empty.
	Head() *Num2

	//-------------------------------------------------------------------------
	// ToSlice returns a plain slice containing all the elements in the collection.
	// This is useful for bespoke iteration etc.
	// For sequences, the order is well defined.
	// For non-sequences (i.e. sets) the first time it is used, order of the elements is not well defined. But
	// the order is stable, which means it will give the same order each subsequent time it is used.
	ToSlice() []*Num2

	// ToList gets all the elements in a in List.
	ToList() Num2List

	// Send sends all elements along a channel of type Num2.
	// For sequences, the order is well defined.
	// For non-sequences (i.e. sets) the first time it is used, order of the elements is not well defined. But
	// the order is stable, which means it will give the same order each subsequent time it is used.
	Send() <-chan *Num2

	//-------------------------------------------------------------------------
	// Exists returns true if there exists at least one element in the collection that matches
	// the predicate supplied.
	Exists(predicate func(*Num2) bool) bool

	// Forall returns true if every element in the collection matches the predicate supplied.
	Forall(predicate func(*Num2) bool) bool

	// Foreach iterates over every element, executing a supplied function against each.
	Foreach(fn func(*Num2))

	//-------------------------------------------------------------------------
	// Filter returns a new Num2Collection whose elements return true for a predicate function.
	// The relative order of the elements in the result is the same as in the
	// original collection.
	Filter(predicate func(*Num2) bool) (result Num2Collection)

	// Partition returns two new Num2Collections whose elements return true or false for the predicate, p.
	// The first consists of all elements that satisfy the predicate and the second consists of
	// all elements that don't. The relative order of the elements in the results is the same as in the
	// original collection.
	Partition(p func(*Num2) bool) (matching Num2Collection, others Num2Collection)

	//-------------------------------------------------------------------------

	// Equals verifies that another Num2Collection has the same size and elements as this one. Also,
	// if the collection is a sequence, the order must be the same.
	// Omitted if Num2 is not comparable.
	Equals(other Num2Collection) bool

	// Contains tests whether a given value is present in the collection.
	// Omitted if Num2 is not comparable.
	Contains(value *Num2) bool

	// Min returns an element of Num2List containing the minimum value, when compared to other elements
	// using a specified comparator function defining ‘less’. For ordered sequences, Min returns the first such element.
	// Panics if the collection is empty.
	Min(less func(*Num2, *Num2) bool) *Num2

	// Max returns an element of Num2List containing the maximum value, when compared to other elements
	// using a specified comparator function defining ‘less’. For ordered sequences, Max returns the first such element.
	// Panics if the collection is empty.
	Max(less func(*Num2, *Num2) bool) *Num2

	//-------------------------------------------------------------------------
	// String gets a string representation of the collection. "[" and "]" surround
	// a comma-separated list of the elements.
	String() string

	// MkString gets a string representation of the collection. "[" and "]" surround a list
	// of the elements joined by the separator you provide.
	MkString(sep string) string

	// MkString3 gets a string representation of the collection. 'pfx' and 'sfx' surround a list
	// of the elements joined by the 'mid' separator you provide.
	MkString3(pfx, mid, sfx string) string
}

//-------------------------------------------------------------------------------------------------
// Num2List is a slice of type *Num2. Use it where you would use []*Num2.
// List values follow a similar pattern to Scala Lists and LinearSeqs in particular.
// Importantly, *none of its methods ever mutate a list*; they merely return new lists where required.
// When a list needs mutating, use normal Go slice operations, e.g. *append()*.
// For comparison with Scala, see e.g. http://www.scala-lang.org/api/2.11.7/#scala.collection.LinearSeq
type Num2List []*Num2

//-------------------------------------------------------------------------------------------------
// NewNum2List constructs a new list containing the supplied values, if any.
func NewNum2List(values ...*Num2) Num2List {
	list := make(Num2List, len(values))
	for i, v := range values {
		list[i] = v
	}
	return list
}

// BuildNum2ListFromChan constructs a new Num2List from a channel that supplies a sequence
// of values until it is closed. The function doesn't return until then.
func BuildNum2ListFromChan(source <-chan *Num2) Num2List {
	result := make(Num2List, 0)
	for v := range source {
		result = append(result, v)
	}
	return result
}

//-------------------------------------------------------------------------------------------------

// Head gets the first element in the list. Head plus Tail include the whole list. Head is the opposite of Last.
// panics if list is empty
func (list Num2List) Head() *Num2 {
	return list[0]
}

// Last gets the last element in the list. Init plus Last include the whole list. Last is the opposite of Head.
// panics if list is empty
func (list Num2List) Last() *Num2 {
	return list[len(list)-1]
}

// Tail gets everything except the head. Head plus Tail include the whole list. Tail is the opposite of Init.
// panics if list is empty
func (list Num2List) Tail() Num2Collection {
	return Num2List(list[1:])
}

// Init gets everything except the last. Init plus Last include the whole list. Init is the opposite of Tail.
// panics if list is empty
func (list Num2List) Init() Num2Collection {
	return Num2List(list[:len(list)-1])
}

// IsEmpty tests whether Num2List is empty.
func (list Num2List) IsEmpty() bool {
	return len(list) == 0
}

// NonEmpty tests whether Num2List is empty.
func (list Num2List) NonEmpty() bool {
	return len(list) > 0
}

// IsSequence returns true for lists.
func (list Num2List) IsSequence() bool {
	return true
}

// IsSet returns false for lists.
func (list Num2List) IsSet() bool {
	return false
}

// ToSlice gets all the list's elements in a plain slice. This is simply a type conversion.
func (list Num2List) ToSlice() []*Num2 {
	return []*Num2(list)
}

// ToList simply returns the list in this case, but is part of the Collection interface.
func (list Num2List) ToList() Num2List {
	return list
}

// Size returns the number of items in the list - an alias of Len().
func (list Num2List) Size() int {
	return len(list)
}

// Len returns the number of items in the list - an alias of Size().
// This is one of the three methods in the standard sort.Interface.
func (list Num2List) Len() int {
	return len(list)
}

// Swap exchanges two elements, which is neceessary during sorting etc.
// This is one of the three methods in the standard sort.Interface.
func (list Num2List) Swap(i, j int) {
	list[i], list[j] = list[j], list[i]
}

// Exists verifies that one or more elements of Num2List return true for the passed func.
func (list Num2List) Exists(fn func(*Num2) bool) bool {
	for _, v := range list {
		if fn(v) {
			return true
		}
	}
	return false
}

// Forall verifies that all elements of Num2List return true for the passed func.
func (list Num2List) Forall(fn func(*Num2) bool) bool {
	for _, v := range list {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Foreach iterates over Num2List and executes the passed func against each element.
func (list Num2List) Foreach(fn func(*Num2)) {
	for _, v := range list {
		fn(v)
	}
}

// Send gets a channel that will send all the elements in order.
func (list Num2List) Send() <-chan *Num2 {
	ch := make(chan *Num2)
	go func() {
		for _, v := range list {
			ch <- v
		}
		close(ch)
	}()
	return ch
}

// Reverse returns a copy of Num2List with all elements in the reverse order.
func (list Num2List) Reverse() Num2List {
	numItems := len(list)
	result := make(Num2List, numItems)
	last := numItems - 1
	for i, v := range list {
		result[last-i] = v
	}
	return result
}

// Shuffle returns a shuffled copy of Num2List, using a version of the Fisher-Yates shuffle.
func (list Num2List) Shuffle() Num2List {
	numItems := len(list)
	result := make(Num2List, numItems)
	copy(result, list)
	for i := 0; i < numItems; i++ {
		r := i + rand.Intn(numItems-i)
		result.Swap(i, r)
	}
	return result
}

// Take returns a new Num2List containing the leading n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num2List) Take(n int) Num2List {
	if n > len(list) {
		return list
	} else {
		return list[0:n]
	}
}

// Drop returns a new Num2List without the leading n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num2List) Drop(n int) Num2List {
	l := len(list)
	if n > l {
		return list[l:]
	} else {
		return list[n:]
	}
}

// TakeLast returns a new Num2List containing the trailing n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num2List) TakeLast(n int) Num2List {
	l := len(list)
	if n > l {
		return list
	} else {
		return list[l-n:]
	}
}

// DropLast returns a new Num2List without the trailing n elements of the source list.
// If n is greater than the size of the list, the whole list is returned.
func (list Num2List) DropLast(n int) Num2List {
	l := len(list)
	if n > l {
		return list[l:]
	} else {
		return list[0 : l-n]
	}
}

// TakeWhile returns a new Num2List containing the leading elements of the source list. Whilst the
// predicate p returns true, elements are added to the result. Once predicate p returns false, all remaining
// elemense are excluded.
func (list Num2List) TakeWhile(p func(*Num2) bool) (result Num2List) {
	for _, v := range list {
		if p(v) {
			result = append(result, v)
		} else {
			return
		}
	}
	return
}

// DropWhile returns a new Num2List containing the trailing elements of the source list. Whilst the
// predicate p returns true, elements are excluded from the result. Once predicate p returns false, all remaining
// elemense are added.
func (list Num2List) DropWhile(p func(*Num2) bool) (result Num2List) {
	adding := false
	for _, v := range list {
		if !p(v) || adding {
			adding = true
			result = append(result, v)
		}
	}
	return
}

// Filter returns a new Num2List whose elements return true for func.
func (list Num2List) Filter(fn func(*Num2) bool) Num2Collection {
	result := make(Num2List, 0, len(list)/2)
	for _, v := range list {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Partition returns two new Num2Lists whose elements return true or false for the predicate, p.
// The first result consists of all elements that satisfy the predicate and the second result consists of
// all elements that don't. The relative order of the elements in the results is the same as in the
// original list.
func (list Num2List) Partition(p func(*Num2) bool) (Num2Collection, Num2Collection) {
	matching := make(Num2List, 0, len(list)/2)
	others := make(Num2List, 0, len(list)/2)
	for _, v := range list {
		if p(v) {
			matching = append(matching, v)
		} else {
			others = append(others, v)
		}
	}
	return matching, others
}

// CountBy gives the number elements of Num2List that return true for the passed predicate.
func (list Num2List) CountBy(predicate func(*Num2) bool) (result int) {
	for _, v := range list {
		if predicate(v) {
			result++
		}
	}
	return
}

// MinBy returns an element of Num2List containing the minimum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such
// element is returned. Panics if there are no elements.
func (list Num2List) MinBy(less func(*Num2, *Num2) bool) (result *Num2) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the minimum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// MaxBy returns an element of Num2List containing the maximum value, when compared to other elements
// using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such
// element is returned. Panics if there are no elements.
func (list Num2List) MaxBy(less func(*Num2, *Num2) bool) (result *Num2) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the maximum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if list[i] != list[m] && !less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// DistinctBy returns a new Num2List whose elements are unique, where equality is defined by a passed func.
func (list Num2List) DistinctBy(equal func(*Num2, *Num2) bool) (result Num2List) {
Outer:
	for _, v := range list {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

// IndexWhere finds the index of the first element satisfying some predicate. If none exists, -1 is returned.
func (list Num2List) IndexWhere(p func(*Num2) bool) int {
	for i, v := range list {
		if p(v) {
			return i
		}
	}
	return -1
}

// IndexWhere2 finds the index of the first element satisfying some predicate at or after some start index.
// If none exists, -1 is returned.
func (list Num2List) IndexWhere2(p func(*Num2) bool, from int) int {
	for i, v := range list {
		if i >= from && p(v) {
			return i
		}
	}
	return -1
}

// LastIndexWhere finds the index of the last element satisfying some predicate.
// If none exists, -1 is returned.
func (list Num2List) LastIndexWhere(p func(*Num2) bool) int {
	for i := len(list) - 1; i >= 0; i-- {
		v := list[i]
		if p(v) {
			return i
		}
	}
	return -1
}

// LastIndexWhere2 finds the index of the last element satisfying some predicate at or after some start index.
// If none exists, -1 is returned.
func (list Num2List) LastIndexWhere2(p func(*Num2) bool, before int) int {
	for i := len(list) - 1; i >= 0; i-- {
		v := list[i]
		if i <= before && p(v) {
			return i
		}
	}
	return -1
}

// These methods require *Num2 be comparable.

// Equals verifies that one or more elements of Num2List return true for the passed func.
func (list Num2List) Equals(other Num2Collection) bool {
	if len(list) != other.Size() {
		return false
	}
	eq := true
	i := 0
	other.Foreach(func(a *Num2) {
		if eq {
			v := list[i]
			if *v != *a {
				eq = false
			}
			i += 1
		}
	})
	return eq
}

// These methods require *Num2 be comparable.

// IndexOf finds the index of the first element specified. If none exists, -1 is returned.
func (list Num2List) IndexOf(value *Num2) int {
	for i, v := range list {
		if *v == *value {
			return i
		}
	}
	return -1
}

// IndexOf2 finds the index of the first element specified at or after some start index.
// If none exists, -1 is returned.
func (list Num2List) IndexOf2(value *Num2, from int) int {
	for i, v := range list {
		if i >= from && *v == *value {
			return i
		}
	}
	return -1
}

// Contains verifies that a given value is contained in Num2List.
func (list Num2List) Contains(value *Num2) bool {
	for _, v := range list {
		if *v == *value {
			return true
		}
	}
	return false
}

// Count gives the number elements of Num2List that match a certain value.
func (list Num2List) Count(value *Num2) (result int) {
	for _, v := range list {
		if *v == *value {
			result++
		}
	}
	return
}

// Distinct returns a new Num2List whose elements are unique, retaining the original order.
func (list Num2List) Distinct() Num2Collection {
	result := make(Num2List, 0)
	appended := make(map[Num2]bool)
	for _, v := range list {
		if !appended[*v] {
			result = append(result, v)
			appended[*v] = true
		}
	}
	return result
}

//-------------------------------------------------------------------------------------------------
// These methods are included when Num2 is not ordered.

// Min returns the first element containing the minimum value, when compared to other elements
// using a specified comparator function defining ‘less’.
// Panics if the collection is empty.
func (list Num2List) Min(less func(*Num2, *Num2) bool) (result *Num2) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the minimum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// Max returns the first element containing the maximum value, when compared to other elements
// using a specified comparator function defining ‘less’.
// Panics if the collection is empty.
func (list Num2List) Max(less func(*Num2, *Num2) bool) (result *Num2) {
	l := len(list)
	if l == 0 {
		panic("Cannot determine the maximum of an empty list.")
	}
	m := 0
	for i := 1; i < l; i++ {
		if list[i] != list[m] && !less(list[i], list[m]) {
			m = i
		}
	}
	result = list[m]
	return
}

// String implements the Stringer interface to render the list as a comma-separated array.
func (list Num2List) String() string {
	return list.MkString3("[", ",", "]")
}

// MkString concatenates the values as a string.
func (list Num2List) MkString(sep string) string {
	return list.MkString3("", sep, "")
}

// MkString3 concatenates the values as a string.
func (list Num2List) MkString3(pfx, mid, sfx string) string {
	b := bytes.Buffer{}
	b.WriteString(pfx)
	l := len(list)
	if l > 0 {
		v := list[0]
		b.WriteString(fmt.Sprintf("%v", *v))
		for i := 1; i < l; i++ {
			v := list[i]
			b.WriteString(mid)
			b.WriteString(fmt.Sprintf("%v", *v))
		}
	}
	b.WriteString(sfx)
	return b.String()
}

// optionForList

// List flags: {Collection:false Sequence:false List:true Option:false Set:false Tag:map[]}
